// ─────────────────────────────────────────────
// Biblioteca de Exercícios para Casa Sem Equipamento
// 22 Padrões de Movimento
// ─────────────────────────────────────────────

import 'home_exercise_model.dart';

final List<HomeExercise> homeExerciseLibrary = [
  // ═══════════════════════════════════════════════════════════════
  // 1. AGACHAMENTO (Dominante de Joelho)
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'squat_chair',
    name: 'Sentar na cadeira',
    nameEn: 'Chair sit',
    pattern: HomeMovementPattern.squat,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    cues: ['Use a cadeira como referência', 'Controle a descida', 'Empurre o chão para levantar'],
    primaryFunction: 'Capacidade de levantar e sentar',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'squat_assisted',
  ),

  HomeExercise(
    id: 'squat_assisted',
    name: 'Agachamento assistido',
    nameEn: 'Assisted squat',
    pattern: HomeMovementPattern.squat,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'calves'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    cues: ['Segure em um apoio estável', 'Desça controladamente', 'Mantenha o peito aberto'],
    primaryFunction: 'Força de membros inferiores com apoio',
    strengthDemand: 0.4,
    mobilityDemand: 0.3,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: 'squat_chair',
    progressionId: 'squat_free',
  ),

  HomeExercise(
    id: 'squat_free',
    name: 'Agachamento livre',
    nameEn: 'Bodyweight squat',
    pattern: HomeMovementPattern.squat,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'calves', 'adductors'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle, HomeBodyRegion.lowerBack],
    cues: ['Pés na largura dos ombros', 'Desça até onde controlar', 'Joelhos alinhados com os pés'],
    primaryFunction: 'Força funcional de membros inferiores',
    strengthDemand: 0.6,
    mobilityDemand: 0.4,
    balanceDemand: 0.3,
    stabilityDemand: 0.4,
    regressionId: 'squat_assisted',
    progressionId: 'squat_pause',
  ),

  HomeExercise(
    id: 'squat_pause',
    name: 'Agachamento com pausa',
    nameEn: 'Pause squat',
    pattern: HomeMovementPattern.squat,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'calves'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle, HomeBodyRegion.lowerBack],
    cues: ['Pause 2-3 segundos na posição mais baixa', 'Mantenha tensão muscular', 'Controle total do movimento'],
    primaryFunction: 'Força e controle em amplitude específica',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'squat_free',
    progressionId: 'squat_split',
  ),

  HomeExercise(
    id: 'squat_split',
    name: 'Agachamento dividido',
    nameEn: 'Split squat',
    pattern: HomeMovementPattern.squat,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'adductors'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    isUnilateral: true,
    cues: ['Posição dividida estável', 'Desça verticalmente', 'Controle o joelho da frente'],
    primaryFunction: 'Força unilateral e controle do joelho',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'squat_pause',
    progressionId: 'squat_bulgarian',
  ),

  HomeExercise(
    id: 'squat_bulgarian',
    name: 'Agachamento búlgaro',
    nameEn: 'Bulgarian split squat',
    pattern: HomeMovementPattern.squat,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'adductors'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    isUnilateral: true,
    cues: ['Pé traseiro elevado', 'Desça controladamente', 'Mantenha o tronco ereto'],
    primaryFunction: 'Força unilateral avançada',
    strengthDemand: 0.8,
    mobilityDemand: 0.5,
    balanceDemand: 0.6,
    stabilityDemand: 0.6,
    regressionId: 'squat_split',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 2. DOMINANTE DE QUADRIL (Hinge)
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'hinge_wall',
    name: 'Hip hinge na parede',
    nameEn: 'Wall hip hinge',
    pattern: HomeMovementPattern.hipHinge,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['erectors', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Costas para a parede', 'Empurre o quadril para trás', 'Toque a parede com o quadril'],
    primaryFunction: 'Aprender o padrão de quadril',
    strengthDemand: 0.2,
    mobilityDemand: 0.3,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'glute_bridge',
  ),

  HomeExercise(
    id: 'glute_bridge',
    name: 'Ponte de glúteos',
    nameEn: 'Glute bridge',
    pattern: HomeMovementPattern.hipHinge,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'erectors'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Deitado com joelhos flexionados', 'Empurre o quadril para cima', 'Aperte os glúteos no topo'],
    primaryFunction: 'Força de extensão do quadril',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: 'hinge_wall',
    progressionId: 'glute_bridge_pause',
  ),

  HomeExercise(
    id: 'glute_bridge_pause',
    name: 'Ponte com pausa',
    nameEn: 'Pause glute bridge',
    pattern: HomeMovementPattern.hipHinge,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Pause 2-3 segundos no topo', 'Mantenha a contração', 'Controle a descida'],
    primaryFunction: 'Força e controle de extensão',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'glute_bridge',
    progressionId: 'good_morning',
  ),

  HomeExercise(
    id: 'good_morning',
    name: 'Good morning com peso corporal',
    nameEn: 'Bodyweight good morning',
    pattern: HomeMovementPattern.hipHinge,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['erectors', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack, HomeBodyRegion.hamstring],
    cues: ['Mãos atrás da cabeça', 'Dobre o quadril para trás', 'Mantenha as costas retas'],
    primaryFunction: 'Força de hinge com amplitude controlada',
    strengthDemand: 0.5,
    mobilityDemand: 0.4,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: 'glute_bridge_pause',
    progressionId: 'glute_bridge_unilateral',
  ),

  HomeExercise(
    id: 'glute_bridge_unilateral',
    name: 'Ponte unilateral',
    nameEn: 'Single leg glute bridge',
    pattern: HomeMovementPattern.hipHinge,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    isUnilateral: true,
    cues: ['Uma perna estendida', 'Empurre com a perna de apoio', 'Mantenha a pelve nivelada'],
    primaryFunction: 'Força unilateral de extensão',
    strengthDemand: 0.7,
    mobilityDemand: 0.3,
    balanceDemand: 0.4,
    stabilityDemand: 0.5,
    regressionId: 'good_morning',
    progressionId: 'good_morning_unilateral',
  ),

  HomeExercise(
    id: 'good_morning_unilateral',
    name: 'Good morning unilateral',
    nameEn: 'Single leg good morning',
    pattern: HomeMovementPattern.hipHinge,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['erectors', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack, HomeBodyRegion.hamstring],
    isUnilateral: true,
    cues: ['Uma perna como apoio', 'Hinge controlado', 'Mantenha o equilíbrio'],
    primaryFunction: 'Força e equilíbrio unilateral',
    strengthDemand: 0.8,
    mobilityDemand: 0.5,
    balanceDemand: 0.6,
    stabilityDemand: 0.6,
    regressionId: 'glute_bridge_unilateral',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 3. EMPURRAR HORIZONTAL
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'pushup_wall',
    name: 'Flexão na parede',
    nameEn: 'Wall push-up',
    pattern: HomeMovementPattern.pushHorizontal,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    secondaryMuscles: ['serratus', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow, HomeBodyRegion.wrist],
    cues: ['Mãos na parede na altura dos ombros', 'Flexione os cotovelos', 'Empurre de volta'],
    primaryFunction: 'Força básica de empurrar',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'pushup_incline',
  ),

  HomeExercise(
    id: 'pushup_incline',
    name: 'Flexão inclinada',
    nameEn: 'Incline push-up',
    pattern: HomeMovementPattern.pushHorizontal,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    secondaryMuscles: ['serratus', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow, HomeBodyRegion.wrist],
    cues: ['Mãos em superfície elevada', 'Corpo alinhado', 'Desça até o peito tocar'],
    primaryFunction: 'Força de empurrar com menor demanda',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: 'pushup_wall',
    progressionId: 'pushup_knees',
  ),

  HomeExercise(
    id: 'pushup_knees',
    name: 'Flexão com joelhos apoiados',
    nameEn: 'Knee push-up',
    pattern: HomeMovementPattern.pushHorizontal,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    secondaryMuscles: ['serratus', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow, HomeBodyRegion.wrist],
    cues: ['Joelhos no chão', 'Corpo alinhado do joelho à cabeça', 'Amplitude completa'],
    primaryFunction: 'Força de empurrar intermediária',
    strengthDemand: 0.5,
    mobilityDemand: 0.3,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: 'pushup_incline',
    progressionId: 'pushup_standard',
  ),

  HomeExercise(
    id: 'pushup_standard',
    name: 'Flexão tradicional',
    nameEn: 'Standard push-up',
    pattern: HomeMovementPattern.pushHorizontal,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    secondaryMuscles: ['serratus', 'core', 'biceps'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow, HomeBodyRegion.wrist],
    cues: ['Mãos na largura dos ombros', 'Corpo reto', 'Desça até o peito quase tocar o chão'],
    primaryFunction: 'Força completa de empurrar horizontal',
    strengthDemand: 0.7,
    mobilityDemand: 0.3,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'pushup_knees',
    progressionId: 'pushup_pause',
  ),

  HomeExercise(
    id: 'pushup_pause',
    name: 'Flexão com pausa',
    nameEn: 'Pause push-up',
    pattern: HomeMovementPattern.pushHorizontal,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    secondaryMuscles: ['serratus', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow, HomeBodyRegion.wrist],
    cues: ['Pause 2-3 segundos na posição baixa', 'Mantenha tensão', 'Empurre explosivamente'],
    primaryFunction: 'Força e controle em amplitude específica',
    strengthDemand: 0.8,
    mobilityDemand: 0.3,
    balanceDemand: 0.3,
    stabilityDemand: 0.6,
    regressionId: 'pushup_standard',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 4. PUXAR HORIZONTAL (Condicional)
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'row_towel',
    name: 'Remada com toalha',
    nameEn: 'Towel row',
    pattern: HomeMovementPattern.pullHorizontal,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['lats', 'rhomboids', 'traps', 'biceps'],
    secondaryMuscles: ['rear_deltoid', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow],
    isConditional: true,
    conditionalRequirement: 'Requer configuração segura com toalha e ponto de fixação',
    cues: ['Toalha fixa em ponto estável', 'Puxe o corpo em direção ao ponto', 'Mantenha o corpo alinhado'],
    primaryFunction: 'Força de puxada horizontal',
    strengthDemand: 0.6,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
  ),

  HomeExercise(
    id: 'row_table',
    name: 'Remada sob mesa',
    nameEn: 'Table row',
    pattern: HomeMovementPattern.pullHorizontal,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['lats', 'rhomboids', 'traps', 'biceps'],
    secondaryMuscles: ['rear_deltoid', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow],
    isConditional: true,
    conditionalRequirement: 'Requer mesa resistente e estável',
    cues: ['Debaixo da mesa', 'Segure a borda', 'Puxe o peito em direção à mesa'],
    primaryFunction: 'Força de puxada horizontal',
    strengthDemand: 0.6,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
  ),

  HomeExercise(
    id: 'superman',
    name: 'Superman',
    nameEn: 'Superman',
    pattern: HomeMovementPattern.pullHorizontal,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['erectors', 'glutes', 'traps', 'rhomboids'],
    secondaryMuscles: ['rear_deltoid', 'core'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.shoulder],
    cues: ['Deitado de barriga para baixo', 'Eleve braços e pernas', 'Segure por 2-3 segundos'],
    primaryFunction: 'Fortalecimento da cadeia posterior',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 5. UNILATERAL / LOCOMOÇÃO
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'march_stationary',
    name: 'Marcha parada',
    nameEn: 'Stationary march',
    pattern: HomeMovementPattern.unilateral,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['quadriceps', 'glutes', 'hip_flexors'],
    secondaryMuscles: ['core', 'calves'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    cues: ['Alterne os joelhos', 'Mantenha o tronco ereto', 'Controle o movimento'],
    primaryFunction: 'Coordenação e ativação muscular básica',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'lunge_assisted',
  ),

  HomeExercise(
    id: 'lunge_assisted',
    name: 'Afundo assistido',
    nameEn: 'Assisted lunge',
    pattern: HomeMovementPattern.unilateral,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'adductors'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    cues: ['Segure em um apoio', 'Dê um passo para trás', 'Desça controladamente'],
    primaryFunction: 'Força unilateral com suporte',
    strengthDemand: 0.4,
    mobilityDemand: 0.3,
    balanceDemand: 0.3,
    stabilityDemand: 0.3,
    regressionId: 'march_stationary',
    progressionId: 'lunge_static',
  ),

  HomeExercise(
    id: 'lunge_static',
    name: 'Afundo estático',
    nameEn: 'Static lunge',
    pattern: HomeMovementPattern.unilateral,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'adductors'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    cues: ['Posição dividida fixa', 'Desça e suba', 'Mantenha o equilíbrio'],
    primaryFunction: 'Força unilateral estável',
    strengthDemand: 0.6,
    mobilityDemand: 0.3,
    balanceDemand: 0.4,
    stabilityDemand: 0.4,
    regressionId: 'lunge_assisted',
    progressionId: 'lunge_reverse',
  ),

  HomeExercise(
    id: 'lunge_reverse',
    name: 'Afundo reverso',
    nameEn: 'Reverse lunge',
    pattern: HomeMovementPattern.unilateral,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'adductors'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    isUnilateral: true,
    cues: ['Passo para trás', 'Desça verticalmente', 'Retorne à posição inicial'],
    primaryFunction: 'Força e controle dinâmico unilateral',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'lunge_static',
    progressionId: 'split_squat',
  ),

  HomeExercise(
    id: 'split_squat',
    name: 'Agachamento dividido',
    nameEn: 'Split squat',
    pattern: HomeMovementPattern.unilateral,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    isUnilateral: true,
    cues: ['Posição dividida', 'Desça verticalmente', 'Controle o joelho da frente'],
    primaryFunction: 'Força unilateral de membros inferiores',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'lunge_reverse',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 6. CORE ANTI-EXTENSÃO
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'plank_wall',
    name: 'Prancha na parede',
    nameEn: 'Wall plank',
    pattern: HomeMovementPattern.coreAntiExtension,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['rectus_abdominis', 'transverse_abdominis'],
    secondaryMuscles: ['obliques', 'erectors'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.lowerBack],
    cues: ['Mãos na parede', 'Corpo reto', 'Ative o abdômen'],
    primaryFunction: 'Estabilidade básica do tronco',
    strengthDemand: 0.2,
    mobilityDemand: 0.1,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: null,
    progressionId: 'plank_incline',
  ),

  HomeExercise(
    id: 'plank_incline',
    name: 'Prancha inclinada',
    nameEn: 'Incline plank',
    pattern: HomeMovementPattern.coreAntiExtension,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['rectus_abdominis', 'transverse_abdominis'],
    secondaryMuscles: ['obliques', 'erectors', 'shoulders'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.lowerBack],
    cues: ['Mãos em superfície elevada', 'Corpo alinhado', 'Resista à extensão'],
    primaryFunction: 'Estabilidade do tronco intermediária',
    strengthDemand: 0.3,
    mobilityDemand: 0.1,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: 'plank_wall',
    progressionId: 'plank_knees',
  ),

  HomeExercise(
    id: 'plank_knees',
    name: 'Prancha com joelhos',
    nameEn: 'Knee plank',
    pattern: HomeMovementPattern.coreAntiExtension,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['rectus_abdominis', 'transverse_abdominis'],
    secondaryMuscles: ['obliques', 'erectors'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.lowerBack],
    cues: ['Joelhos no chão', 'Linha reta do joelho à cabeça', 'Respire normalmente'],
    primaryFunction: 'Estabilidade do tronco com menor demanda',
    strengthDemand: 0.4,
    mobilityDemand: 0.1,
    balanceDemand: 0.2,
    stabilityDemand: 0.5,
    regressionId: 'plank_incline',
    progressionId: 'plank_standard',
  ),

  HomeExercise(
    id: 'plank_standard',
    name: 'Prancha tradicional',
    nameEn: 'Standard plank',
    pattern: HomeMovementPattern.coreAntiExtension,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['rectus_abdominis', 'transverse_abdominis'],
    secondaryMuscles: ['obliques', 'erectors', 'shoulders'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.lowerBack],
    cues: ['Antebraços no chão', 'Corpo reto', 'Ative todo o core'],
    primaryFunction: 'Estabilidade completa do tronco',
    strengthDemand: 0.6,
    mobilityDemand: 0.1,
    balanceDemand: 0.3,
    stabilityDemand: 0.6,
    regressionId: 'plank_knees',
    progressionId: 'dead_bug',
  ),

  HomeExercise(
    id: 'dead_bug',
    name: 'Dead bug',
    nameEn: 'Dead bug',
    pattern: HomeMovementPattern.coreAntiExtension,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['rectus_abdominis', 'transverse_abdominis'],
    secondaryMuscles: ['obliques', 'hip_flexors'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip],
    cues: ['Deitado com braços e pernas para cima', 'Estenda braço e perna opostos', 'Mantenha a lombar no chão'],
    primaryFunction: 'Controle anti-extensão dinâmico',
    strengthDemand: 0.5,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.6,
    regressionId: 'plank_standard',
    progressionId: 'bird_dog',
  ),

  HomeExercise(
    id: 'bird_dog',
    name: 'Bird dog',
    nameEn: 'Bird dog',
    pattern: HomeMovementPattern.coreAntiExtension,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['erectors', 'glutes', 'rectus_abdominis'],
    secondaryMuscles: ['obliques', 'traps', 'rhomboids'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip, HomeBodyRegion.shoulder],
    cues: ['Quatro apoios', 'Estenda braço e perna opostos', 'Mantenha o tronco estável'],
    primaryFunction: 'Estabilidade e coordenação contralateral',
    strengthDemand: 0.5,
    mobilityDemand: 0.2,
    balanceDemand: 0.4,
    stabilityDemand: 0.7,
    regressionId: 'dead_bug',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 7. PANTURRILHA
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'calf_bilateral_support',
    name: 'Elevação de panturrilha bilateral com apoio',
    nameEn: 'Supported bilateral calf raise',
    pattern: HomeMovementPattern.calf,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: ['tibialis_posterior', 'peroneals'],
    demandRegions: [HomeBodyRegion.ankle],
    cues: ['Segure em um apoio', 'Eleve os calcanhares', 'Desça controladamente'],
    primaryFunction: 'Força básica da panturrilha',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'calf_bilateral_free',
  ),

  HomeExercise(
    id: 'calf_bilateral_free',
    name: 'Elevação de panturrilha em pé',
    nameEn: 'Standing calf raise',
    pattern: HomeMovementPattern.calf,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: ['tibialis_posterior', 'peroneals'],
    demandRegions: [HomeBodyRegion.ankle],
    cues: ['Sem apoio', 'Eleve os calcanhares', 'Pause no topo'],
    primaryFunction: 'Força de panturrilha sem suporte',
    strengthDemand: 0.5,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.3,
    regressionId: 'calf_bilateral_support',
    progressionId: 'calf_bilateral_pause',
  ),

  HomeExercise(
    id: 'calf_bilateral_pause',
    name: 'Elevação com pausa no topo',
    nameEn: 'Pause calf raise',
    pattern: HomeMovementPattern.calf,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: ['tibialis_posterior'],
    demandRegions: [HomeBodyRegion.ankle],
    cues: ['Pause 2-3 segundos no topo', 'Mantenha a contração', 'Desça lentamente'],
    primaryFunction: 'Força e controle de panturrilha',
    strengthDemand: 0.6,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.4,
    regressionId: 'calf_bilateral_free',
    progressionId: 'calf_unilateral_support',
  ),

  HomeExercise(
    id: 'calf_unilateral_support',
    name: 'Elevação unilateral com apoio',
    nameEn: 'Supported single leg calf raise',
    pattern: HomeMovementPattern.calf,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: ['tibialis_posterior'],
    demandRegions: [HomeBodyRegion.ankle],
    isUnilateral: true,
    cues: ['Uma perna', 'Segure em apoio', 'Controle o movimento'],
    primaryFunction: 'Força unilateral de panturrilha',
    strengthDemand: 0.7,
    mobilityDemand: 0.2,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'calf_bilateral_pause',
    progressionId: 'calf_unilateral_free',
  ),

  HomeExercise(
    id: 'calf_unilateral_free',
    name: 'Elevação unilateral sem apoio',
    nameEn: 'Single leg calf raise',
    pattern: HomeMovementPattern.calf,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: ['tibialis_posterior'],
    demandRegions: [HomeBodyRegion.ankle],
    isUnilateral: true,
    cues: ['Uma perna sem apoio', 'Amplitude completa', 'Controle total'],
    primaryFunction: 'Força e equilíbrio unilateral',
    strengthDemand: 0.8,
    mobilityDemand: 0.2,
    balanceDemand: 0.6,
    stabilityDemand: 0.6,
    regressionId: 'calf_unilateral_support',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 8. EXTENSÃO DE QUADRIL / GLÚTEO
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'hip_ext_bridge',
    name: 'Ponte de glúteo',
    nameEn: 'Glute bridge',
    pattern: HomeMovementPattern.hipExtension,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'erectors', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Deitado com joelhos flexionados', 'Empurre o quadril para cima', 'Aperte os glúteos'],
    primaryFunction: 'Força básica de extensão do quadril',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'hip_ext_bridge_support',
  ),

  HomeExercise(
    id: 'hip_ext_bridge_support',
    name: 'Ponte com apoio dos pés',
    nameEn: 'Foot supported glute bridge',
    pattern: HomeMovementPattern.hipExtension,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.hip],
    cues: ['Pés apoiados em superfície', 'Empurre o quadril', 'Mantenha a posição'],
    primaryFunction: 'Ativação de glúteos com suporte',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: 'hip_ext_bridge',
    progressionId: 'hip_ext_bridge_pause',
  ),

  HomeExercise(
    id: 'hip_ext_bridge_pause',
    name: 'Ponte com pausa no topo',
    nameEn: 'Pause glute bridge',
    pattern: HomeMovementPattern.hipExtension,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Pause 2-3 segundos no topo', 'Contraia os glúteos', 'Desça controladamente'],
    primaryFunction: 'Força e controle de extensão',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'hip_ext_bridge_support',
    progressionId: 'hip_ext_bridge_amplitude',
  ),

  HomeExercise(
    id: 'hip_ext_bridge_amplitude',
    name: 'Ponte com maior amplitude',
    nameEn: 'Full range glute bridge',
    pattern: HomeMovementPattern.hipExtension,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Amplitude máxima', 'Controle a extensão', 'Evite hiperextensão lombar'],
    primaryFunction: 'Força de extensão com amplitude completa',
    strengthDemand: 0.5,
    mobilityDemand: 0.3,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: 'hip_ext_bridge_pause',
    progressionId: 'hip_ext_bridge_unilateral',
  ),

  HomeExercise(
    id: 'hip_ext_bridge_unilateral',
    name: 'Ponte unilateral',
    nameEn: 'Single leg glute bridge',
    pattern: HomeMovementPattern.hipExtension,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    isUnilateral: true,
    cues: ['Uma perna estendida', 'Empurre com a perna de apoio', 'Mantenha a pelve nivelada'],
    primaryFunction: 'Força unilateral de extensão',
    strengthDemand: 0.7,
    mobilityDemand: 0.3,
    balanceDemand: 0.4,
    stabilityDemand: 0.5,
    regressionId: 'hip_ext_bridge_amplitude',
    progressionId: 'hip_ext_unilateral_pause',
  ),

  HomeExercise(
    id: 'hip_ext_unilateral_pause',
    name: 'Ponte unilateral com pausa',
    nameEn: 'Pause single leg glute bridge',
    pattern: HomeMovementPattern.hipExtension,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    isUnilateral: true,
    cues: ['Pause no topo', 'Contraia o glúteo', 'Controle total'],
    primaryFunction: 'Força e controle unilateral avançado',
    strengthDemand: 0.8,
    mobilityDemand: 0.3,
    balanceDemand: 0.5,
    stabilityDemand: 0.6,
    regressionId: 'hip_ext_bridge_unilateral',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 9. CORE LATERAL / ANTI-FLEXÃO LATERAL
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'side_plank_wall',
    name: 'Prancha lateral na parede',
    nameEn: 'Wall side plank',
    pattern: HomeMovementPattern.coreLateral,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['obliques', 'quadratus_lumborum'],
    secondaryMuscles: ['gluteus_medius', 'transverse_abdominis'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.hip],
    cues: ['Lateral na parede', 'Mantenha o corpo alinhado', 'Ative os oblíquos'],
    primaryFunction: 'Estabilidade lateral básica',
    strengthDemand: 0.2,
    mobilityDemand: 0.1,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: null,
    progressionId: 'side_plank_knees',
  ),

  HomeExercise(
    id: 'side_plank_knees',
    name: 'Prancha lateral com joelhos',
    nameEn: 'Knee side plank',
    pattern: HomeMovementPattern.coreLateral,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['obliques', 'quadratus_lumborum'],
    secondaryMuscles: ['gluteus_medius', 'transverse_abdominis'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.hip],
    cues: ['Joelhos apoiados', 'Linha reta', 'Resista à inclinação'],
    primaryFunction: 'Estabilidade lateral intermediária',
    strengthDemand: 0.3,
    mobilityDemand: 0.1,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: 'side_plank_wall',
    progressionId: 'side_plank_standard',
  ),

  HomeExercise(
    id: 'side_plank_standard',
    name: 'Prancha lateral tradicional',
    nameEn: 'Standard side plank',
    pattern: HomeMovementPattern.coreLateral,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['obliques', 'quadratus_lumborum'],
    secondaryMuscles: ['gluteus_medius', 'transverse_abdominis'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.hip],
    cues: ['Antebraço no chão', 'Corpo reto', 'Mantenha a posição'],
    primaryFunction: 'Estabilidade lateral completa',
    strengthDemand: 0.5,
    mobilityDemand: 0.1,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'side_plank_knees',
    progressionId: 'side_plank_leg_lift',
  ),

  HomeExercise(
    id: 'side_plank_leg_lift',
    name: 'Prancha lateral com elevação da perna',
    nameEn: 'Side plank with leg lift',
    pattern: HomeMovementPattern.coreLateral,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['obliques', 'gluteus_medius'],
    secondaryMuscles: ['quadratus_lumborum', 'transverse_abdominis'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.hip],
    cues: ['Prancha lateral estável', 'Eleve a perna superior', 'Mantenha o quadril alto'],
    primaryFunction: 'Estabilidade lateral com demanda adicional',
    strengthDemand: 0.7,
    mobilityDemand: 0.2,
    balanceDemand: 0.4,
    stabilityDemand: 0.6,
    regressionId: 'side_plank_standard',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 10. CORE ROTACIONAL / ANTI-ROTAÇÃO
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'dead_bug_rotation',
    name: 'Dead bug básico',
    nameEn: 'Basic dead bug',
    pattern: HomeMovementPattern.coreRotation,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['obliques', 'transverse_abdominis'],
    secondaryMuscles: ['rectus_abdominis', 'hip_flexors'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip],
    cues: ['Deitado com braços e pernas para cima', 'Estenda um braço e a perna oposta', 'Mantenha a lombar no chão'],
    primaryFunction: 'Controle rotacional básico',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: null,
    progressionId: 'bird_dog_rotation',
  ),

  HomeExercise(
    id: 'bird_dog_rotation',
    name: 'Bird dog',
    nameEn: 'Bird dog',
    pattern: HomeMovementPattern.coreRotation,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['obliques', 'erectors', 'glutes'],
    secondaryMuscles: ['transverse_abdominis', 'traps', 'rhomboids'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip, HomeBodyRegion.shoulder],
    cues: ['Quatro apoios', 'Estenda braço e perna opostos', 'Mantenha o tronco estável'],
    primaryFunction: 'Estabilidade e coordenação contralateral',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'dead_bug_rotation',
    progressionId: 'bird_dog_pause',
  ),

  HomeExercise(
    id: 'bird_dog_pause',
    name: 'Bird dog com pausa',
    nameEn: 'Pause bird dog',
    pattern: HomeMovementPattern.coreRotation,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['obliques', 'erectors', 'glutes'],
    secondaryMuscles: ['transverse_abdominis'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip, HomeBodyRegion.shoulder],
    cues: ['Pause 2-3 segundos', 'Mantenha a posição', 'Controle total'],
    primaryFunction: 'Controle rotacional com tempo sob tensão',
    strengthDemand: 0.5,
    mobilityDemand: 0.2,
    balanceDemand: 0.4,
    stabilityDemand: 0.6,
    regressionId: 'bird_dog_rotation',
    progressionId: 'bear_hold',
  ),

  HomeExercise(
    id: 'bear_hold',
    name: 'Bear hold',
    nameEn: 'Bear hold',
    pattern: HomeMovementPattern.coreRotation,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['obliques', 'transverse_abdominis', 'hip_flexors'],
    secondaryMuscles: ['rectus_abdominis', 'shoulders'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Quatro apoios com joelhos levantados', 'Mantenha a posição', 'Ative o core'],
    primaryFunction: 'Estabilidade anti-rotação isométrica',
    strengthDemand: 0.6,
    mobilityDemand: 0.2,
    balanceDemand: 0.4,
    stabilityDemand: 0.7,
    regressionId: 'bird_dog_pause',
    progressionId: 'bear_shoulder_tap',
  ),

  HomeExercise(
    id: 'bear_shoulder_tap',
    name: 'Bear shoulder tap',
    nameEn: 'Bear shoulder tap',
    pattern: HomeMovementPattern.coreRotation,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['obliques', 'transverse_abdominis'],
    secondaryMuscles: ['shoulders', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.hip, HomeBodyRegion.lowerBack],
    cues: ['Posição de bear', 'Toque o ombro oposto', 'Mantenha o quadril estável'],
    primaryFunction: 'Controle rotacional dinâmico',
    strengthDemand: 0.7,
    mobilityDemand: 0.2,
    balanceDemand: 0.5,
    stabilityDemand: 0.7,
    regressionId: 'bear_hold',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 11. CORE FLEXÃO DE TRONCO
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'core_isometric',
    name: 'Contração abdominal isométrica',
    nameEn: 'Isometric abdominal contraction',
    pattern: HomeMovementPattern.coreFlexion,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['rectus_abdominis'],
    secondaryMuscles: ['transverse_abdominis'],
    demandRegions: [HomeBodyRegion.lowerBack],
    cues: ['Deitado com joelhos flexionados', 'Contraia o abdômen', 'Mantenha por 10-15 segundos'],
    primaryFunction: 'Ativação abdominal básica',
    strengthDemand: 0.2,
    mobilityDemand: 0.1,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'dead_bug_flexion',
  ),

  HomeExercise(
    id: 'dead_bug_flexion',
    name: 'Dead bug básico',
    nameEn: 'Basic dead bug',
    pattern: HomeMovementPattern.coreFlexion,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['rectus_abdominis'],
    secondaryMuscles: ['obliques', 'hip_flexors'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip],
    cues: ['Deitado com braços e pernas para cima', 'Estenda braço e perna opostos', 'Mantenha a lombar no chão'],
    primaryFunction: 'Controle abdominal dinâmico',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: 'core_isometric',
    progressionId: 'crunch_short',
  ),

  HomeExercise(
    id: 'crunch_short',
    name: 'Crunch curto',
    nameEn: 'Short crunch',
    pattern: HomeMovementPattern.coreFlexion,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['rectus_abdominis'],
    secondaryMuscles: ['obliques'],
    demandRegions: [HomeBodyRegion.lowerBack],
    cues: ['Deitado com joelhos flexionados', 'Eleve os ombros levemente', 'Contraia o abdômen'],
    primaryFunction: 'Força abdominal com amplitude limitada',
    strengthDemand: 0.3,
    mobilityDemand: 0.1,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'dead_bug_flexion',
    progressionId: 'crunch_full',
  ),

  HomeExercise(
    id: 'crunch_full',
    name: 'Crunch',
    nameEn: 'Crunch',
    pattern: HomeMovementPattern.coreFlexion,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['rectus_abdominis'],
    secondaryMuscles: ['obliques'],
    demandRegions: [HomeBodyRegion.lowerBack],
    cues: ['Amplitude completa', 'Controle o movimento', 'Evite puxar o pescoço'],
    primaryFunction: 'Força abdominal completa',
    strengthDemand: 0.5,
    mobilityDemand: 0.1,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'crunch_short',
    progressionId: 'reverse_crunch',
  ),

  HomeExercise(
    id: 'reverse_crunch',
    name: 'Reverse crunch',
    nameEn: 'Reverse crunch',
    pattern: HomeMovementPattern.coreFlexion,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['rectus_abdominis', 'hip_flexors'],
    secondaryMuscles: ['obliques'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip],
    cues: ['Deitado com pernas para cima', 'Eleve o quadril do chão', 'Controle a descida'],
    primaryFunction: 'Força abdominal inferior',
    strengthDemand: 0.6,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: 'crunch_full',
    progressionId: 'v_up',
  ),

  HomeExercise(
    id: 'v_up',
    name: 'V-up',
    nameEn: 'V-up',
    pattern: HomeMovementPattern.coreFlexion,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['rectus_abdominis', 'hip_flexors'],
    secondaryMuscles: ['obliques'],
    demandRegions: [HomeBodyRegion.lowerBack, HomeBodyRegion.hip],
    cues: ['Deitado com braços e pernas estendidos', 'Eleve simultaneamente', 'Toque os pés com as mãos'],
    primaryFunction: 'Força abdominal avançada',
    strengthDemand: 0.8,
    mobilityDemand: 0.3,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'reverse_crunch',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 12. ABDUÇÃO DE QUADRIL
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'hip_abduction_lying',
    name: 'Abdução de quadril deitado',
    nameEn: 'Lying hip abduction',
    pattern: HomeMovementPattern.hipAbduction,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['gluteus_medius', 'gluteus_minimus'],
    secondaryMuscles: ['tensor_fasciae_latae'],
    demandRegions: [HomeBodyRegion.hip],
    cues: ['Deitado de lado', 'Eleve a perna superior', 'Controle a descida'],
    primaryFunction: 'Força básica de abdução',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'clamshell',
  ),

  HomeExercise(
    id: 'clamshell',
    name: 'Clamshell',
    nameEn: 'Clamshell',
    pattern: HomeMovementPattern.hipAbduction,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['gluteus_medius'],
    secondaryMuscles: ['gluteus_minimus'],
    demandRegions: [HomeBodyRegion.hip],
    cues: ['Deitado de lado com joelhos flexionados', 'Abra os joelhos como uma concha', 'Mantenha os pés juntos'],
    primaryFunction: 'Ativação do glúteo médio',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'hip_abduction_lying',
    progressionId: 'hip_abduction_standing',
  ),

  HomeExercise(
    id: 'hip_abduction_standing',
    name: 'Abdução em pé com apoio',
    nameEn: 'Supported standing hip abduction',
    pattern: HomeMovementPattern.hipAbduction,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['gluteus_medius', 'gluteus_minimus'],
    secondaryMuscles: ['tensor_fasciae_latae', 'core'],
    demandRegions: [HomeBodyRegion.hip],
    cues: ['Segure em um apoio', 'Eleve a perna lateralmente', 'Mantenha o tronco ereto'],
    primaryFunction: 'Força de abdução em posição funcional',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.4,
    regressionId: 'clamshell',
    progressionId: 'hip_abduction_controlled',
  ),

  HomeExercise(
    id: 'hip_abduction_controlled',
    name: 'Abdução unilateral controlada',
    nameEn: 'Controlled hip abduction',
    pattern: HomeMovementPattern.hipAbduction,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['gluteus_medius', 'gluteus_minimus'],
    secondaryMuscles: ['core'],
    demandRegions: [HomeBodyRegion.hip],
    isUnilateral: true,
    cues: ['Sem apoio', 'Controle total', 'Mantenha a pelve nivelada'],
    primaryFunction: 'Força e controle de abdução',
    strengthDemand: 0.6,
    mobilityDemand: 0.2,
    balanceDemand: 0.4,
    stabilityDemand: 0.5,
    regressionId: 'hip_abduction_standing',
    progressionId: 'lateral_walk',
  ),

  HomeExercise(
    id: 'lateral_walk',
    name: 'Caminhada lateral',
    nameEn: 'Lateral walk',
    pattern: HomeMovementPattern.hipAbduction,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['gluteus_medius'],
    secondaryMuscles: ['gluteus_minimus', 'quadriceps', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.knee],
    cues: ['Passos laterais controlados', 'Mantenha os joelhos alinhados', 'Ative os glúteos'],
    primaryFunction: 'Força dinâmica de abdução',
    strengthDemand: 0.6,
    mobilityDemand: 0.3,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'hip_abduction_controlled',
    progressionId: 'lateral_walk_squat',
  ),

  HomeExercise(
    id: 'lateral_walk_squat',
    name: 'Caminhada lateral em agachamento',
    nameEn: 'Lateral walk squat',
    pattern: HomeMovementPattern.hipAbduction,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['gluteus_medius', 'quadriceps'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.knee],
    cues: ['Posição de agachamento', 'Passos laterais', 'Mantenha a posição baixa'],
    primaryFunction: 'Força e resistência de abdução',
    strengthDemand: 0.8,
    mobilityDemand: 0.4,
    balanceDemand: 0.6,
    stabilityDemand: 0.6,
    regressionId: 'lateral_walk',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 13. ADUÇÃO DE QUADRIL
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'hip_adduction_lying',
    name: 'Adução deitado com amplitude pequena',
    nameEn: 'Lying hip adduction',
    pattern: HomeMovementPattern.hipAdduction,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['adductors'],
    secondaryMuscles: ['gracilis', 'pectineus'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.groin],
    cues: ['Deitado de lado', 'Cruze a perna superior para frente', 'Aproxime da linha média'],
    primaryFunction: 'Força básica de adução',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'hip_adduction_lateral',
  ),

  HomeExercise(
    id: 'hip_adduction_lateral',
    name: 'Adução lateral deitado',
    nameEn: 'Lateral lying adduction',
    pattern: HomeMovementPattern.hipAdduction,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['adductors'],
    secondaryMuscles: ['gracilis'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.groin],
    cues: ['Deitado de lado', 'Eleve a perna inferior', 'Controle o movimento'],
    primaryFunction: 'Força de adução isolada',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'hip_adduction_lying',
    progressionId: 'hip_adduction_isometric',
  ),

  HomeExercise(
    id: 'hip_adduction_isometric',
    name: 'Adução isométrica com bola/almofada',
    nameEn: 'Isometric adduction with ball',
    pattern: HomeMovementPattern.hipAdduction,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['adductors'],
    secondaryMuscles: ['gracilis', 'pectineus'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.groin],
    cues: ['Bola ou almofada entre os joelhos', 'Comprima por 10-15 segundos', 'Mantenha a pressão'],
    primaryFunction: 'Força isométrica de adução',
    strengthDemand: 0.3,
    mobilityDemand: 0.1,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'hip_adduction_lateral',
    progressionId: 'copenhagen_plank_support',
  ),

  HomeExercise(
    id: 'copenhagen_plank_support',
    name: 'Copenhagen plank com apoio amplo',
    nameEn: 'Supported Copenhagen plank',
    pattern: HomeMovementPattern.hipAdduction,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['adductors', 'obliques'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.groin, HomeBodyRegion.shoulder],
    cues: ['Antebraço no chão', 'Joelho apoiado em superfície', 'Mantenha o corpo alinhado'],
    primaryFunction: 'Força de adução com carga parcial',
    strengthDemand: 0.5,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'hip_adduction_isometric',
    progressionId: 'copenhagen_plank_knee',
  ),

  HomeExercise(
    id: 'copenhagen_plank_knee',
    name: 'Copenhagen plank com joelho apoiado',
    nameEn: 'Knee supported Copenhagen plank',
    pattern: HomeMovementPattern.hipAdduction,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['adductors', 'obliques'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.groin, HomeBodyRegion.shoulder],
    cues: ['Joelho apoiado na superfície', 'Mantenha a posição', 'Ative os adutores'],
    primaryFunction: 'Força de adução intermediária',
    strengthDemand: 0.6,
    mobilityDemand: 0.2,
    balanceDemand: 0.4,
    stabilityDemand: 0.6,
    regressionId: 'copenhagen_plank_support',
    progressionId: 'copenhagen_plank_full',
  ),

  HomeExercise(
    id: 'copenhagen_plank_full',
    name: 'Copenhagen plank completo',
    nameEn: 'Full Copenhagen plank',
    pattern: HomeMovementPattern.hipAdduction,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['adductors', 'obliques'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.groin, HomeBodyRegion.shoulder],
    cues: ['Pé apoiado na superfície', 'Corpo reto', 'Mantenha a posição'],
    primaryFunction: 'Força completa de adução',
    strengthDemand: 0.8,
    mobilityDemand: 0.3,
    balanceDemand: 0.5,
    stabilityDemand: 0.7,
    regressionId: 'copenhagen_plank_knee',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 14. EXTENSÃO DE JOELHO / QUADRÍCEPS
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'chair_sit_stand',
    name: 'Sentar e levantar da cadeira',
    nameEn: 'Chair sit to stand',
    pattern: HomeMovementPattern.kneeExtension,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    cues: ['Use a cadeira como referência', 'Controle a descida', 'Empurre o chão para levantar'],
    primaryFunction: 'Força funcional básica',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'partial_squat',
  ),

  HomeExercise(
    id: 'partial_squat',
    name: 'Agachamento parcial',
    nameEn: 'Partial squat',
    pattern: HomeMovementPattern.kneeExtension,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    cues: ['Amplitude pequena', 'Controle o movimento', 'Mantenha o joelho alinhado'],
    primaryFunction: 'Força de extensão com amplitude limitada',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: 'chair_sit_stand',
    progressionId: 'squat_knee_ext',
  ),

  HomeExercise(
    id: 'squat_knee_ext',
    name: 'Agachamento',
    nameEn: 'Squat',
    pattern: HomeMovementPattern.kneeExtension,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'calves'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    cues: ['Amplitude conforme capacidade', 'Joelhos alinhados', 'Descida controlada'],
    primaryFunction: 'Força completa de extensão',
    strengthDemand: 0.6,
    mobilityDemand: 0.4,
    balanceDemand: 0.3,
    stabilityDemand: 0.4,
    regressionId: 'partial_squat',
    progressionId: 'wall_sit',
  ),

  HomeExercise(
    id: 'wall_sit',
    name: 'Wall sit',
    nameEn: 'Wall sit',
    pattern: HomeMovementPattern.kneeExtension,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    cues: ['Costas na parede', 'Coxas paralelas ao chão', 'Mantenha a posição'],
    primaryFunction: 'Força isométrica de quadríceps',
    strengthDemand: 0.5,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'squat_knee_ext',
    progressionId: 'split_squat_knee_ext',
  ),

  HomeExercise(
    id: 'split_squat_knee_ext',
    name: 'Split squat',
    nameEn: 'Split squat',
    pattern: HomeMovementPattern.kneeExtension,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    isUnilateral: true,
    cues: ['Posição dividida', 'Desça verticalmente', 'Controle o joelho da frente'],
    primaryFunction: 'Força unilateral de extensão',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'wall_sit',
    progressionId: 'pistol_squat_regression',
  ),

  HomeExercise(
    id: 'pistol_squat_regression',
    name: 'Pistol squat regressão',
    nameEn: 'Pistol squat regression',
    pattern: HomeMovementPattern.kneeExtension,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'calves'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    isUnilateral: true,
    cues: ['Uma perna', 'Apoio se necessário', 'Amplitude conforme capacidade'],
    primaryFunction: 'Força unilateral avançada',
    strengthDemand: 0.9,
    mobilityDemand: 0.5,
    balanceDemand: 0.7,
    stabilityDemand: 0.7,
    regressionId: 'split_squat_knee_ext',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 15. FLEXÃO DE JOELHO / POSTERIORES
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'glute_bridge_hamstring',
    name: 'Ponte de glúteos',
    nameEn: 'Glute bridge',
    pattern: HomeMovementPattern.kneeFlexion,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['erectors', 'core'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.hamstring],
    cues: ['Deitado com joelhos flexionados', 'Empurre o quadril para cima', 'Ative os posteriores'],
    primaryFunction: 'Força básica dos posteriores',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'hamstring_slide_short',
  ),

  HomeExercise(
    id: 'hamstring_slide_short',
    name: 'Deslizamento dos calcanhares com pequena amplitude',
    nameEn: 'Short heel slide',
    pattern: HomeMovementPattern.kneeFlexion,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hamstring, HomeBodyRegion.hip],
    cues: ['Deitado com pés no chão', 'Deslize os calcanhares', 'Amplitude pequena'],
    primaryFunction: 'Força excêntrica dos posteriores',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.1,
    stabilityDemand: 0.3,
    regressionId: 'glute_bridge_hamstring',
    progressionId: 'hamstring_walkout_short',
  ),

  HomeExercise(
    id: 'hamstring_walkout_short',
    name: 'Hamstring walkout curto',
    nameEn: 'Short hamstring walkout',
    pattern: HomeMovementPattern.kneeFlexion,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hamstring, HomeBodyRegion.hip],
    cues: ['Ponte de glúteos', 'Ande com os pés para frente', 'Mantenha o quadril alto'],
    primaryFunction: 'Força excêntrica progressiva',
    strengthDemand: 0.5,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
    regressionId: 'hamstring_slide_short',
    progressionId: 'hamstring_walkout',
  ),

  HomeExercise(
    id: 'hamstring_walkout',
    name: 'Hamstring walkout',
    nameEn: 'Hamstring walkout',
    pattern: HomeMovementPattern.kneeFlexion,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hamstring, HomeBodyRegion.hip],
    cues: ['Amplitude completa', 'Controle total', 'Mantenha o quadril alto'],
    primaryFunction: 'Força excêntrica completa',
    strengthDemand: 0.7,
    mobilityDemand: 0.3,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'hamstring_walkout_short',
    progressionId: 'nordic_regression',
  ),

  HomeExercise(
    id: 'nordic_regression',
    name: 'Nordic hamstring regressivo',
    nameEn: 'Nordic hamstring regression',
    pattern: HomeMovementPattern.kneeFlexion,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'core'],
    demandRegions: [HomeBodyRegion.hamstring, HomeBodyRegion.knee],
    cues: ['Apoio nos pés', 'Descida controlada', 'Use as mãos para auxiliar'],
    primaryFunction: 'Força excêntrica avançada',
    strengthDemand: 0.9,
    mobilityDemand: 0.3,
    balanceDemand: 0.4,
    stabilityDemand: 0.6,
    regressionId: 'hamstring_walkout',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 16. EMPURRAR VERTICAL
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'wall_press',
    name: 'Wall press',
    nameEn: 'Wall press',
    pattern: HomeMovementPattern.pushVertical,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['deltoids', 'triceps'],
    secondaryMuscles: ['upper_chest', 'traps'],
    demandRegions: [HomeBodyRegion.shoulder],
    cues: ['Mãos na parede na altura dos ombros', 'Empurre para cima', 'Controle o movimento'],
    primaryFunction: 'Força básica de empurrar vertical',
    strengthDemand: 0.2,
    mobilityDemand: 0.3,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'incline_shoulder_press',
  ),

  HomeExercise(
    id: 'incline_shoulder_press',
    name: 'Incline shoulder press',
    nameEn: 'Incline shoulder press',
    pattern: HomeMovementPattern.pushVertical,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['deltoids', 'triceps'],
    secondaryMuscles: ['upper_chest', 'traps'],
    demandRegions: [HomeBodyRegion.shoulder],
    cues: ['Inclinação moderada', 'Empurre para cima', 'Controle a descida'],
    primaryFunction: 'Força de empurrar vertical intermediária',
    strengthDemand: 0.4,
    mobilityDemand: 0.4,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: 'wall_press',
    progressionId: 'pike_pushup_regression',
  ),

  HomeExercise(
    id: 'pike_pushup_regression',
    name: 'Pike push-up regressivo',
    nameEn: 'Pike push-up regression',
    pattern: HomeMovementPattern.pushVertical,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['deltoids', 'triceps'],
    secondaryMuscles: ['upper_chest', 'traps', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.wrist],
    cues: ['Quadril elevado', 'Desça a cabeça em direção ao chão', 'Empurre de volta'],
    primaryFunction: 'Força de empurrar vertical com carga parcial',
    strengthDemand: 0.6,
    mobilityDemand: 0.5,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
    regressionId: 'incline_shoulder_press',
    progressionId: 'pike_pushup',
  ),

  HomeExercise(
    id: 'pike_pushup',
    name: 'Pike push-up',
    nameEn: 'Pike push-up',
    pattern: HomeMovementPattern.pushVertical,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['deltoids', 'triceps'],
    secondaryMuscles: ['upper_chest', 'traps', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.wrist],
    cues: ['Posição de V invertido', 'Desça a cabeça', 'Empurre com força'],
    primaryFunction: 'Força de empurrar vertical completa',
    strengthDemand: 0.7,
    mobilityDemand: 0.5,
    balanceDemand: 0.4,
    stabilityDemand: 0.6,
    regressionId: 'pike_pushup_regression',
    progressionId: 'pike_pushup_amplitude',
  ),

  HomeExercise(
    id: 'pike_pushup_amplitude',
    name: 'Pike push-up com maior amplitude',
    nameEn: 'Full range pike push-up',
    pattern: HomeMovementPattern.pushVertical,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['deltoids', 'triceps'],
    secondaryMuscles: ['upper_chest', 'traps', 'core'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.wrist],
    cues: ['Amplitude máxima', 'Controle total', 'Empurre explosivamente'],
    primaryFunction: 'Força avançada de empurrar vertical',
    strengthDemand: 0.8,
    mobilityDemand: 0.6,
    balanceDemand: 0.5,
    stabilityDemand: 0.7,
    regressionId: 'pike_pushup',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 17. PUXAR VERTICAL (Condicional)
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'pullup_bar',
    name: 'Barra fixa',
    nameEn: 'Pull-up',
    pattern: HomeMovementPattern.pullVertical,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['rhomboids', 'traps', 'rear_deltoid', 'forearms'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow, HomeBodyRegion.wrist],
    isConditional: true,
    conditionalRequirement: 'Requer barra fixa segura',
    cues: ['Pegada na largura dos ombros', 'Puxe até o queixo passar a barra', 'Controle a descida'],
    primaryFunction: 'Força completa de puxada vertical',
    strengthDemand: 0.9,
    mobilityDemand: 0.4,
    balanceDemand: 0.3,
    stabilityDemand: 0.5,
  ),

  HomeExercise(
    id: 'pullup_assisted',
    name: 'Chin-up assistido',
    nameEn: 'Assisted chin-up',
    pattern: HomeMovementPattern.pullVertical,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['rhomboids', 'traps'],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.elbow],
    isConditional: true,
    conditionalRequirement: 'Requer barra fixa e apoio para os pés',
    cues: ['Use os pés para auxiliar', 'Foque na fase excêntrica', 'Progrida gradualmente'],
    primaryFunction: 'Força de puxada com assistência',
    strengthDemand: 0.6,
    mobilityDemand: 0.3,
    balanceDemand: 0.2,
    stabilityDemand: 0.4,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 18. LOCOMOÇÃO / DESLOCAMENTO
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'march_support',
    name: 'Marcha com apoio',
    nameEn: 'Supported march',
    pattern: HomeMovementPattern.locomotion,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['hip_flexors', 'quadriceps'],
    secondaryMuscles: ['core', 'calves'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.knee],
    cues: ['Segure em um apoio', 'Alterne os joelhos', 'Mantenha o ritmo'],
    primaryFunction: 'Coordenação básica de locomoção',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.2,
    stabilityDemand: 0.2,
    regressionId: null,
    progressionId: 'march_knee_lift',
  ),

  HomeExercise(
    id: 'march_knee_lift',
    name: 'Marcha com elevação de joelho',
    nameEn: 'High knee march',
    pattern: HomeMovementPattern.locomotion,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['hip_flexors', 'quadriceps'],
    secondaryMuscles: ['core', 'calves'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.knee],
    cues: ['Eleve os joelhos', 'Mantenha o tronco ereto', 'Braços coordenados'],
    primaryFunction: 'Coordenação e ativação muscular',
    strengthDemand: 0.3,
    mobilityDemand: 0.3,
    balanceDemand: 0.3,
    stabilityDemand: 0.3,
    regressionId: 'march_support',
    progressionId: 'lateral_movement',
  ),

  HomeExercise(
    id: 'lateral_movement',
    name: 'Deslocamento lateral',
    nameEn: 'Lateral movement',
    pattern: HomeMovementPattern.locomotion,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['gluteus_medius', 'quadriceps'],
    secondaryMuscles: ['core', 'calves'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.knee],
    cues: ['Passos laterais', 'Mantenha os joelhos alinhados', 'Controle o movimento'],
    primaryFunction: 'Locomoção lateral',
    strengthDemand: 0.4,
    mobilityDemand: 0.3,
    balanceDemand: 0.4,
    stabilityDemand: 0.4,
    regressionId: 'march_knee_lift',
    progressionId: 'march_fast',
  ),

  HomeExercise(
    id: 'march_fast',
    name: 'Marcha rápida',
    nameEn: 'Fast march',
    pattern: HomeMovementPattern.locomotion,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['hip_flexors', 'quadriceps', 'glutes'],
    secondaryMuscles: ['core', 'calves'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.knee],
    cues: ['Velocidade aumentada', 'Coordenação dos braços', 'Mantenha o controle'],
    primaryFunction: 'Locomoção com maior demanda',
    strengthDemand: 0.5,
    mobilityDemand: 0.3,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'lateral_movement',
    progressionId: 'multidirectional_movement',
  ),

  HomeExercise(
    id: 'multidirectional_movement',
    name: 'Deslocamentos multidirecionais',
    nameEn: 'Multidirectional movement',
    pattern: HomeMovementPattern.locomotion,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['hip_flexors', 'quadriceps', 'glutes'],
    secondaryMuscles: ['core', 'calves', 'adductors'],
    demandRegions: [HomeBodyRegion.hip, HomeBodyRegion.knee, HomeBodyRegion.ankle],
    cues: ['Mova-se em diferentes direções', 'Mude de direção rapidamente', 'Controle a desaceleração'],
    primaryFunction: 'Agilidade e coordenação avançada',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.7,
    stabilityDemand: 0.7,
    regressionId: 'march_fast',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 19. CONDICIONAMENTO CARDIORRESPIRATÓRIO
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'walking',
    name: 'Caminhada',
    nameEn: 'Walking',
    pattern: HomeMovementPattern.conditioning,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['legs'],
    secondaryMuscles: ['core'],
    demandRegions: [],
    cues: ['Ritmo confortável', 'Braços coordenados', 'Postura ereta'],
    primaryFunction: 'Condicionamento de baixa intensidade',
    strengthDemand: 0.1,
    mobilityDemand: 0.1,
    balanceDemand: 0.1,
    stabilityDemand: 0.1,
    impactLevel: 0.1,
    regressionId: null,
    progressionId: 'step_touch',
  ),

  HomeExercise(
    id: 'step_touch',
    name: 'Step touch',
    nameEn: 'Step touch',
    pattern: HomeMovementPattern.conditioning,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['legs'],
    secondaryMuscles: ['core'],
    demandRegions: [],
    cues: ['Passos laterais', 'Toque o pé no chão', 'Mantenha o ritmo'],
    primaryFunction: 'Ativação cardiovascular leve',
    strengthDemand: 0.1,
    mobilityDemand: 0.1,
    balanceDemand: 0.2,
    stabilityDemand: 0.2,
    impactLevel: 0.1,
    regressionId: 'walking',
    progressionId: 'march_fast_conditioning',
  ),

  HomeExercise(
    id: 'march_fast_conditioning',
    name: 'Marcha rápida',
    nameEn: 'Fast march',
    pattern: HomeMovementPattern.conditioning,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['legs'],
    secondaryMuscles: ['core'],
    demandRegions: [],
    cues: ['Velocidade aumentada', 'Joelhos altos', 'Braços ativos'],
    primaryFunction: 'Condicionamento moderado',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.3,
    impactLevel: 0.2,
    regressionId: 'step_touch',
    progressionId: 'jumping_jacks',
  ),

  HomeExercise(
    id: 'jumping_jacks',
    name: 'Polichinelo',
    nameEn: 'Jumping jacks',
    pattern: HomeMovementPattern.conditioning,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['legs', 'shoulders'],
    secondaryMuscles: ['core'],
    demandRegions: [HomeBodyRegion.shoulder],
    cues: ['Salte abrindo os braços e pernas', 'Mantenha o ritmo', 'Aterrissagem suave'],
    primaryFunction: 'Condicionamento cardiovascular',
    strengthDemand: 0.3,
    mobilityDemand: 0.3,
    balanceDemand: 0.4,
    stabilityDemand: 0.4,
    impactLevel: 0.4,
    regressionId: 'march_fast_conditioning',
    progressionId: 'high_knees',
  ),

  HomeExercise(
    id: 'high_knees',
    name: 'Skipping',
    nameEn: 'High knees',
    pattern: HomeMovementPattern.conditioning,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['hip_flexors', 'quadriceps'],
    secondaryMuscles: ['core', 'calves'],
    demandRegions: [],
    cues: ['Joelhos altos', 'Braços coordenados', 'Mantenha o ritmo'],
    primaryFunction: 'Condicionamento de alta intensidade',
    strengthDemand: 0.5,
    mobilityDemand: 0.3,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    impactLevel: 0.5,
    regressionId: 'jumping_jacks',
    progressionId: 'burpee_regression',
  ),

  HomeExercise(
    id: 'burpee_regression',
    name: 'Burpee regressivo',
    nameEn: 'Burpee regression',
    pattern: HomeMovementPattern.conditioning,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    demandRegions: [HomeBodyRegion.shoulder, HomeBodyRegion.knee],
    cues: ['Versão simplificada', 'Controle o movimento', 'Adapte conforme capacidade'],
    primaryFunction: 'Condicionamento de alta intensidade',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.6,
    stabilityDemand: 0.6,
    impactLevel: 0.6,
    regressionId: 'high_knees',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 20. POTÊNCIA / MOVIMENTOS EXPLOSIVOS
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'calf_raise_fast',
    name: 'Elevação rápida de panturrilha',
    nameEn: 'Fast calf raise',
    pattern: HomeMovementPattern.power,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: [],
    demandRegions: [HomeBodyRegion.ankle],
    cues: ['Suba rapidamente', 'Desça controladamente', 'Intenção de velocidade'],
    primaryFunction: 'Força explosiva básica',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.3,
    impactLevel: 0.2,
    regressionId: null,
    progressionId: 'chair_stand_fast',
  ),

  HomeExercise(
    id: 'chair_stand_fast',
    name: 'Sentar e levantar com intenção rápida',
    nameEn: 'Fast sit to stand',
    pattern: HomeMovementPattern.power,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    cues: ['Levante rapidamente', 'Sentar controladamente', 'Intenção de velocidade'],
    primaryFunction: 'Força funcional explosiva',
    strengthDemand: 0.4,
    mobilityDemand: 0.2,
    balanceDemand: 0.3,
    stabilityDemand: 0.3,
    impactLevel: 0.2,
    regressionId: 'calf_raise_fast',
    progressionId: 'squat_fast',
  ),

  HomeExercise(
    id: 'squat_fast',
    name: 'Agachamento com subida rápida',
    nameEn: 'Fast squat',
    pattern: HomeMovementPattern.power,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip],
    cues: ['Suba explosivamente', 'Desça controladamente', 'Mantenha o controle'],
    primaryFunction: 'Força explosiva de membros inferiores',
    strengthDemand: 0.6,
    mobilityDemand: 0.3,
    balanceDemand: 0.4,
    stabilityDemand: 0.4,
    impactLevel: 0.3,
    regressionId: 'chair_stand_fast',
    progressionId: 'squat_jump',
  ),

  HomeExercise(
    id: 'squat_jump',
    name: 'Squat jump',
    nameEn: 'Squat jump',
    pattern: HomeMovementPattern.power,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    cues: ['Agache e salte', 'Aterrissagem suave', 'Controle a desaceleração'],
    primaryFunction: 'Potência de membros inferiores',
    strengthDemand: 0.7,
    mobilityDemand: 0.4,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    impactLevel: 0.6,
    regressionId: 'squat_fast',
    progressionId: 'pogo_jump',
  ),

  HomeExercise(
    id: 'pogo_jump',
    name: 'Pogo jump',
    nameEn: 'Pogo jump',
    pattern: HomeMovementPattern.power,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['calves', 'ankles'],
    secondaryMuscles: ['core'],
    demandRegions: [HomeBodyRegion.ankle],
    cues: ['Saltos pequenos e rápidos', 'Use os tornozelos', 'Mantenha o ritmo'],
    primaryFunction: 'Reatividade do tornozelo',
    strengthDemand: 0.6,
    mobilityDemand: 0.3,
    balanceDemand: 0.6,
    stabilityDemand: 0.6,
    impactLevel: 0.7,
    regressionId: 'squat_jump',
    progressionId: 'unilateral_jump',
  ),

  HomeExercise(
    id: 'unilateral_jump',
    name: 'Saltos unilaterais',
    nameEn: 'Single leg jumps',
    pattern: HomeMovementPattern.power,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['quadriceps', 'glutes', 'calves'],
    secondaryMuscles: ['hamstrings', 'core'],
    demandRegions: [HomeBodyRegion.knee, HomeBodyRegion.hip, HomeBodyRegion.ankle],
    isUnilateral: true,
    cues: ['Uma perna', 'Aterrissagem controlada', 'Progrida gradualmente'],
    primaryFunction: 'Potência unilateral avançada',
    strengthDemand: 0.9,
    mobilityDemand: 0.5,
    balanceDemand: 0.8,
    stabilityDemand: 0.8,
    impactLevel: 0.8,
    regressionId: 'pogo_jump',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 21. EQUILÍBRIO / CONTROLE MOTOR
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'bipodal_support',
    name: 'Apoio bipodal',
    nameEn: 'Bipodal support',
    pattern: HomeMovementPattern.balance,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['core', 'ankles'],
    secondaryMuscles: ['legs'],
    demandRegions: [HomeBodyRegion.ankle, HomeBodyRegion.hip],
    cues: ['Pés na largura dos ombros', 'Mantenha a posição', 'Olhe para um ponto fixo'],
    primaryFunction: 'Equilíbrio básico',
    strengthDemand: 0.1,
    mobilityDemand: 0.1,
    balanceDemand: 0.3,
    stabilityDemand: 0.3,
    regressionId: null,
    progressionId: 'weight_transfer',
  ),

  HomeExercise(
    id: 'weight_transfer',
    name: 'Transferência de peso',
    nameEn: 'Weight transfer',
    pattern: HomeMovementPattern.balance,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['core', 'ankles', 'legs'],
    secondaryMuscles: [],
    demandRegions: [HomeBodyRegion.ankle, HomeBodyRegion.hip],
    cues: ['Transfira o peso de um pé para o outro', 'Mantenha o controle', 'Movimento suave'],
    primaryFunction: 'Controle dinâmico de equilíbrio',
    strengthDemand: 0.1,
    mobilityDemand: 0.1,
    balanceDemand: 0.4,
    stabilityDemand: 0.4,
    regressionId: 'bipodal_support',
    progressionId: 'unipodal_support',
  ),

  HomeExercise(
    id: 'unipodal_support',
    name: 'Apoio unipodal com apoio',
    nameEn: 'Supported single leg stand',
    pattern: HomeMovementPattern.balance,
    difficulty: HomeDifficulty.level2,
    primaryMuscles: ['core', 'ankles', 'glutes'],
    secondaryMuscles: ['legs'],
    demandRegions: [HomeBodyRegion.ankle, HomeBodyRegion.hip],
    cues: ['Segure em um apoio', 'Uma perna', 'Mantenha a pelve nivelada'],
    primaryFunction: 'Equilíbrio unilateral com suporte',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.5,
    stabilityDemand: 0.5,
    regressionId: 'weight_transfer',
    progressionId: 'controlled_walk',
  ),

  HomeExercise(
    id: 'controlled_walk',
    name: 'Marcha controlada',
    nameEn: 'Controlled walk',
    pattern: HomeMovementPattern.balance,
    difficulty: HomeDifficulty.level3,
    primaryMuscles: ['core', 'ankles', 'legs'],
    secondaryMuscles: [],
    demandRegions: [HomeBodyRegion.ankle, HomeBodyRegion.hip],
    cues: ['Passos lentos e controlados', 'Mantenha o equilíbrio', 'Pé na frente do outro'],
    primaryFunction: 'Equilíbrio dinâmico',
    strengthDemand: 0.2,
    mobilityDemand: 0.2,
    balanceDemand: 0.6,
    stabilityDemand: 0.6,
    regressionId: 'unipodal_support',
    progressionId: 'unipodal_free',
  ),

  HomeExercise(
    id: 'unipodal_free',
    name: 'Apoio unipodal livre',
    nameEn: 'Single leg stand',
    pattern: HomeMovementPattern.balance,
    difficulty: HomeDifficulty.level4,
    primaryMuscles: ['core', 'ankles', 'glutes'],
    secondaryMuscles: ['legs'],
    demandRegions: [HomeBodyRegion.ankle, HomeBodyRegion.hip],
    cues: ['Sem apoio', 'Uma perna', 'Mantenha a posição por 30 segundos'],
    primaryFunction: 'Equilíbrio unilateral completo',
    strengthDemand: 0.3,
    mobilityDemand: 0.2,
    balanceDemand: 0.7,
    stabilityDemand: 0.7,
    regressionId: 'controlled_walk',
    progressionId: 'unipodal_movement',
  ),

  HomeExercise(
    id: 'unipodal_movement',
    name: 'Apoio unipodal com movimento dos membros',
    nameEn: 'Single leg stand with limb movement',
    pattern: HomeMovementPattern.balance,
    difficulty: HomeDifficulty.level5,
    primaryMuscles: ['core', 'ankles', 'glutes'],
    secondaryMuscles: ['legs'],
    demandRegions: [HomeBodyRegion.ankle, HomeBodyRegion.hip],
    cues: ['Uma perna', 'Mova os braços e perna livre', 'Mantenha o equilíbrio'],
    primaryFunction: 'Equilíbrio avançado com demanda adicional',
    strengthDemand: 0.4,
    mobilityDemand: 0.3,
    balanceDemand: 0.8,
    stabilityDemand: 0.8,
    regressionId: 'unipodal_free',
    progressionId: null,
  ),

  // ═══════════════════════════════════════════════════════════════
  // 22. MOBILIDADE FUNCIONAL
  // ═══════════════════════════════════════════════════════════════
  HomeExercise(
    id: 'ankle_mobility',
    name: 'Mobilidade de tornozelo na parede',
    nameEn: 'Ankle mobility wall stretch',
    pattern: HomeMovementPattern.mobility,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['calves', 'ankles'],
    secondaryMuscles: [],
    demandRegions: [HomeBodyRegion.ankle],
    cues: ['Joelho em direção à parede', 'Calcanhar no chão', 'Sinta o alongamento'],
    primaryFunction: 'Melhorar dorsiflexão do tornozelo',
    strengthDemand: 0.0,
    mobilityDemand: 0.6,
    balanceDemand: 0.1,
    stabilityDemand: 0.1,
    regressionId: null,
    progressionId: 'hip_flexor_stretch',
  ),

  HomeExercise(
    id: 'hip_flexor_stretch',
    name: 'Alongamento/mobilidade de flexores do quadril',
    nameEn: 'Hip flexor stretch',
    pattern: HomeMovementPattern.mobility,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['hip_flexors'],
    secondaryMuscles: ['quadriceps'],
    demandRegions: [HomeBodyRegion.hip],
    cues: ['Posição de afundo', 'Empurre o quadril para frente', 'Sinta o alongamento'],
    primaryFunction: 'Melhorar extensão do quadril',
    strengthDemand: 0.0,
    mobilityDemand: 0.6,
    balanceDemand: 0.2,
    stabilityDemand: 0.2,
    regressionId: 'ankle_mobility',
    progressionId: 'thoracic_rotation',
  ),

  HomeExercise(
    id: 'thoracic_rotation',
    name: 'Rotação torácica',
    nameEn: 'Thoracic rotation',
    pattern: HomeMovementPattern.mobility,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['thoracic_spine'],
    secondaryMuscles: ['obliques'],
    demandRegions: [HomeBodyRegion.shoulder],
    cues: ['Quatro apoios', 'Rote o tronco', 'Mantenha o quadril estável'],
    primaryFunction: 'Melhorar mobilidade torácica',
    strengthDemand: 0.0,
    mobilityDemand: 0.6,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: 'hip_flexor_stretch',
    progressionId: 'shoulder_mobility',
  ),

  HomeExercise(
    id: 'shoulder_mobility',
    name: 'Mobilidade de ombro na parede',
    nameEn: 'Shoulder wall mobility',
    pattern: HomeMovementPattern.mobility,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    demandRegions: [HomeBodyRegion.shoulder],
    cues: ['Mãos na parede', 'Deslize os braços para cima', 'Mantenha o contato'],
    primaryFunction: 'Melhorar elevação do ombro',
    strengthDemand: 0.0,
    mobilityDemand: 0.6,
    balanceDemand: 0.1,
    stabilityDemand: 0.2,
    regressionId: 'thoracic_rotation',
    progressionId: 'wrist_mobility',
  ),

  HomeExercise(
    id: 'wrist_mobility',
    name: 'Mobilidade de punho',
    nameEn: 'Wrist mobility',
    pattern: HomeMovementPattern.mobility,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['wrists', 'forearms'],
    secondaryMuscles: [],
    demandRegions: [HomeBodyRegion.wrist],
    cues: ['Estenda e flexione os punhos', 'Rote suavemente', 'Não force'],
    primaryFunction: 'Melhorar amplitude do punho',
    strengthDemand: 0.0,
    mobilityDemand: 0.5,
    balanceDemand: 0.0,
    stabilityDemand: 0.1,
    regressionId: 'shoulder_mobility',
    progressionId: 'squat_assist_mobility',
  ),

  HomeExercise(
    id: 'squat_assist_mobility',
    name: 'Agachamento assistido em amplitude confortável',
    nameEn: 'Assisted squat mobility',
    pattern: HomeMovementPattern.mobility,
    difficulty: HomeDifficulty.level1,
    primaryMuscles: ['ankles', 'hips', 'thoracic'],
    secondaryMuscles: ['legs'],
    demandRegions: [HomeBodyRegion.ankle, HomeBodyRegion.hip],
    cues: ['Segure em um apoio', 'Desça até amplitude confortável', 'Mantenha por 20-30 segundos'],
    primaryFunction: 'Mobilidade combinada para agachamento',
    strengthDemand: 0.1,
    mobilityDemand: 0.7,
    balanceDemand: 0.2,
    stabilityDemand: 0.3,
    regressionId: 'wrist_mobility',
    progressionId: null,
  ),
];
