import * as admin from "firebase-admin";

// ═══════════════════════════════════════════════════════════════
// SEED SCRIPT — Banco Global de Exercícios no Firestore
//
// Uso:
//   1. Coloque sua service-account.json em firebase/
//   2. cd firebase
//   3. npx ts-node functions/src/seed_exercises.ts
//
// Popula a coleção global `exercises/` com todos os exercícios
// da biblioteca científica. Leitura pública para usuários auth,
// escrita bloqueada (apenas Admin SDK).
// ═══════════════════════════════════════════════════════════════

const serviceAccount = require("../../service-account.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

interface Exercise {
  id: string;
  name: string;
  nameEn: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  movementPattern: string;
  equipment: string[];
  environment: string[];
  category: string;
  difficulty: string;
  restrictions: string[];
  repRangeMin: number;
  repRangeMax: number;
  isUnilateral: boolean;
  gifUrl: string | null;
  cues: string[];
  substituteIds: string[];
  progressionIds: string[];
  regressionIds: string[];
  tags: string[];
}

const exercises: Exercise[] = [

  // ── PEITO ─────────────────────────────────────────────────────

  {
    id: "chest_supino_barra",
    name: "Supino Reto com Barra",
    nameEn: "Barbell Bench Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    movementPattern: "push_horizontal",
    equipment: ["barbell", "bench"],
    environment: ["full_gym", "basic_gym"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["shoulder"],
    repRangeMin: 5, repRangeMax: 10,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Escápulas retraídas e deprimidas", "Pés firmes no chão", "Barra desce ao mamilo — não à clavícula", "Cotovelos a 45–75° do tronco"],
    substituteIds: ["chest_supino_halteres", "chest_flexao_archer"],
    progressionIds: [],
    regressionIds: ["chest_supino_halteres"],
    tags: ["compound", "chest", "push", "pr_candidate"],
  },
  {
    id: "chest_supino_halteres",
    name: "Supino Reto com Halteres",
    nameEn: "Dumbbell Bench Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    movementPattern: "push_horizontal",
    equipment: ["dumbbell", "bench"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Amplitude maior que a barra — halteres descem além do peito", "Halteres paralelos no topo", "Controle a descida em 2–3s"],
    substituteIds: ["chest_supino_barra", "chest_flexao"],
    progressionIds: ["chest_supino_barra"],
    regressionIds: ["chest_flexao"],
    tags: ["compound", "chest", "push", "home_friendly"],
  },
  {
    id: "chest_supino_inclinado_halteres",
    name: "Supino Inclinado com Halteres",
    nameEn: "Incline Dumbbell Press",
    primaryMuscles: ["upper_chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    movementPattern: "push_incline",
    equipment: ["dumbbell", "bench"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "beginner",
    restrictions: ["shoulder"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Banco a 30–45°", "ROM completa — halteres até a linha do peito", "Não deixe os halteres passarem das orelhas"],
    substituteIds: ["chest_supino_inclinado_barra"],
    progressionIds: [],
    regressionIds: [],
    tags: ["compound", "upper_chest", "push"],
  },
  {
    id: "chest_supino_inclinado_barra",
    name: "Supino Inclinado com Barra",
    nameEn: "Incline Barbell Press",
    primaryMuscles: ["upper_chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    movementPattern: "push_incline",
    equipment: ["barbell", "bench"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["shoulder"],
    repRangeMin: 6, repRangeMax: 10,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Banco a 30° — não mais que 45°", "Pegada ligeiramente mais fechada que o supino reto"],
    substituteIds: ["chest_supino_inclinado_halteres"],
    progressionIds: [],
    regressionIds: [],
    tags: ["compound", "upper_chest", "push"],
  },
  {
    id: "chest_flexao",
    name: "Flexão de Braços",
    nameEn: "Push Up",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "core"],
    movementPattern: "push_horizontal",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_bodyweight", "home_dumbbell", "outdoor"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 25,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Corpo reto — não deixe o quadril cair", "Cotovelos a 45° do tronco", "ROM completa — peito toca o chão", "Core ativado durante todo o movimento"],
    substituteIds: [],
    progressionIds: ["chest_flexao_diamante", "chest_flexao_archer"],
    regressionIds: ["chest_flexao_inclinada_parede"],
    tags: ["bodyweight", "chest", "push", "home_friendly", "no_equipment"],
  },
  {
    id: "chest_flexao_inclinada_parede",
    name: "Flexão Inclinada na Parede",
    nameEn: "Wall Push Up",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps"],
    movementPattern: "push_horizontal",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_bodyweight", "home_dumbbell", "outdoor"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 15, repRangeMax: 30,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Mãos na parede à altura do peito", "Corpo reto", "ROM completa"],
    substituteIds: [],
    progressionIds: ["chest_flexao"],
    regressionIds: [],
    tags: ["bodyweight", "chest", "push", "beginner_only", "no_equipment"],
  },
  {
    id: "chest_flexao_diamante",
    name: "Flexão Diamante",
    nameEn: "Diamond Push Up",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest"],
    movementPattern: "push_horizontal",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_bodyweight", "home_dumbbell", "outdoor"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["wrist"],
    repRangeMin: 8, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Polegares e indicadores formam um diamante", "Cotovelos colados ao corpo na descida"],
    substituteIds: [],
    progressionIds: ["chest_flexao_archer"],
    regressionIds: ["chest_flexao"],
    tags: ["bodyweight", "triceps", "chest", "push", "no_equipment"],
  },
  {
    id: "chest_flexao_archer",
    name: "Flexão Arqueiro",
    nameEn: "Archer Push Up",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    movementPattern: "push_horizontal",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_bodyweight", "home_dumbbell", "outdoor"],
    category: "compound",
    difficulty: "advanced",
    restrictions: ["shoulder", "wrist"],
    repRangeMin: 5, repRangeMax: 10,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Braço dominante flexiona, braço oposto estendido", "Mova o peso lateralmente", "Precursor da flexão de um braço"],
    substituteIds: [],
    progressionIds: ["chest_flexao_um_braco"],
    regressionIds: ["chest_flexao"],
    tags: ["bodyweight", "chest", "push", "advanced", "no_equipment"],
  },
  {
    id: "chest_crucifixo_halteres",
    name: "Crucifixo com Halteres",
    nameEn: "Dumbbell Fly",
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["dumbbell", "bench"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: ["shoulder"],
    repRangeMin: 12, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Leve flexão de cotovelo fixa durante todo o movimento", "ROM completa — braços até a linha do ombro", "Sinta o estiramento no peito na descida"],
    substituteIds: ["chest_peck_deck"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "chest", "stretch"],
  },
  {
    id: "chest_peck_deck",
    name: "Peck Deck (Máquina)",
    nameEn: "Pec Deck Machine",
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["machine"],
    environment: ["full_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: ["shoulder"],
    repRangeMin: 12, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Cotovelos na altura dos ombros", "ROM completa — sinta a contração no centro", "Ajuste o banco para ombros relaxados"],
    substituteIds: ["chest_crucifixo_halteres"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "chest", "machine"],
  },

  // ── COSTAS ────────────────────────────────────────────────────

  {
    id: "back_puxada_frente",
    name: "Puxada Frontal (Pulley)",
    nameEn: "Lat Pulldown",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    movementPattern: "pull_vertical",
    equipment: ["cable"],
    environment: ["full_gym", "basic_gym"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 8, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — braços completamente estendidos no topo", "Puxe com os cotovelos — não com as mãos", "Peito alto, leve inclinação para trás", "Barra desce até a linha do queixo"],
    substituteIds: [],
    progressionIds: ["back_barra_fixa"],
    regressionIds: [],
    tags: ["compound", "back", "pull_vertical", "lats"],
  },
  {
    id: "back_barra_fixa",
    name: "Barra Fixa (Pronada)",
    nameEn: "Pull Up",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    movementPattern: "pull_vertical",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "compound",
    difficulty: "advanced",
    restrictions: ["shoulder"],
    repRangeMin: 4, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Deprima as escápulas antes de iniciar a puxada", "ROM completa — braços totalmente estendidos na descida", "Queixo acima da barra no topo", "Controle excêntrico de 2–3s"],
    substituteIds: ["back_puxada_frente"],
    progressionIds: [],
    regressionIds: ["back_puxada_frente"],
    tags: ["bodyweight", "back", "pull_vertical", "advanced", "pr_candidate"],
  },
  {
    id: "back_remada_serrote",
    name: "Remada Unilateral (Serrote)",
    nameEn: "Single Arm Dumbbell Row",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    movementPattern: "pull_horizontal",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Costas paralelas ao chão ou leve inclinação", "ROM completa — halter até o quadril", "Retrai a escápula no topo — pausa de 1s", "Controle a descida em 2–3s"],
    substituteIds: ["back_remada_barra"],
    progressionIds: [],
    regressionIds: [],
    tags: ["compound", "back", "pull_horizontal", "unilateral", "home_friendly"],
  },
  {
    id: "back_remada_barra",
    name: "Remada Curvada com Barra",
    nameEn: "Barbell Row",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "core"],
    movementPattern: "pull_horizontal",
    equipment: ["barbell"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["lower_back"],
    repRangeMin: 5, repRangeMax: 10,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Tronco a 45° — não paralelo ao chão", "Barra raspa a perna durante todo o movimento", "ROM completa — barra até o umbigo", "Core engajado — não arredonde a lombar"],
    substituteIds: ["back_remada_serrote", "back_remada_maquina"],
    progressionIds: [],
    regressionIds: ["back_remada_serrote"],
    tags: ["compound", "back", "pull_horizontal", "strength"],
  },
  {
    id: "back_remada_baixa_cabo",
    name: "Remada Baixa (Cabo/Triângulo)",
    nameEn: "Seated Cable Row",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delt"],
    movementPattern: "pull_horizontal",
    equipment: ["cable"],
    environment: ["full_gym", "basic_gym"],
    category: "compound",
    difficulty: "beginner",
    restrictions: ["lower_back"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — braços totalmente estendidos na frente", "Não balance o tronco", "Aproxime as escápulas no final — pausa 1s"],
    substituteIds: ["back_remada_serrote"],
    progressionIds: [],
    regressionIds: [],
    tags: ["compound", "back", "pull_horizontal", "mid_back"],
  },
  {
    id: "back_remada_maquina",
    name: "Remada Máquina (Chest Supported)",
    nameEn: "Chest Supported Row",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delt"],
    movementPattern: "pull_horizontal",
    equipment: ["machine"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Peito apoiado elimina compensação lombar", "ROM completa", "Foque na retração das escápulas"],
    substituteIds: ["back_remada_serrote"],
    progressionIds: [],
    regressionIds: [],
    tags: ["compound", "back", "machine", "lower_back_safe"],
  },
  {
    id: "back_facepull",
    name: "Face Pull (Polia)",
    nameEn: "Cable Face Pull",
    primaryMuscles: ["rear_delt"],
    secondaryMuscles: ["back", "rotator_cuff"],
    movementPattern: "pull_horizontal",
    equipment: ["cable"],
    environment: ["full_gym", "basic_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 15, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Corda na altura dos olhos", "Puxe para a testa — não para o pescoço", "Rotação externa do ombro no final", "Excelente para saúde do manguito rotador"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "rear_delt", "shoulder_health", "rehab_friendly"],
  },

  // ── OMBROS ────────────────────────────────────────────────────

  {
    id: "shoulder_press_halteres",
    name: "Desenvolvimento com Halteres",
    nameEn: "Dumbbell Shoulder Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    movementPattern: "push_vertical",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "beginner",
    restrictions: ["shoulder"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Halteres alinhados com as orelhas", "ROM completa — cotovelos totalmente estendidos no topo", "Não trave o cotovelo", "Core ativado"],
    substituteIds: ["shoulder_press_arnold"],
    progressionIds: ["shoulder_press_militar"],
    regressionIds: [],
    tags: ["compound", "shoulders", "push_vertical", "home_friendly"],
  },
  {
    id: "shoulder_press_arnold",
    name: "Desenvolvimento Arnold",
    nameEn: "Arnold Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    movementPattern: "push_vertical",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["shoulder"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Começa com palmas para dentro no baixo", "Rotação externa progressiva na subida", "Ativa todas as cabeças do deltóide"],
    substituteIds: ["shoulder_press_halteres"],
    progressionIds: [],
    regressionIds: ["shoulder_press_halteres"],
    tags: ["compound", "shoulders", "push_vertical", "all_heads"],
  },
  {
    id: "shoulder_press_militar",
    name: "Desenvolvimento Militar (Barra)",
    nameEn: "Overhead Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    movementPattern: "push_vertical",
    equipment: ["barbell"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "advanced",
    restrictions: ["shoulder", "lower_back"],
    repRangeMin: 5, repRangeMax: 8,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Trava o core antes de empurrar", "Barra desce até o queixo", "Cabeça recua para a barra passar", "ROM completa — braços totalmente estendidos no topo"],
    substituteIds: ["shoulder_press_halteres"],
    progressionIds: [],
    regressionIds: ["shoulder_press_halteres"],
    tags: ["compound", "shoulders", "push_vertical", "strength"],
  },
  {
    id: "shoulder_elevacao_lateral",
    name: "Elevação Lateral com Halteres",
    nameEn: "Dumbbell Lateral Raise",
    primaryMuscles: ["side_delt"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: ["shoulder"],
    repRangeMin: 12, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — braços até a linha do ombro", "Polegar levemente para baixo no topo", "Sem balançar o tronco", "Controle excêntrico de 3s"],
    substituteIds: ["shoulder_elevacao_lateral_cabo"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "side_delt", "home_friendly"],
  },
  {
    id: "shoulder_elevacao_lateral_cabo",
    name: "Elevação Lateral no Cabo",
    nameEn: "Cable Lateral Raise",
    primaryMuscles: ["side_delt"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["cable"],
    environment: ["full_gym", "basic_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: ["shoulder"],
    repRangeMin: 12, repRangeMax: 20,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Polia na altura do tornozelo", "Tensão constante durante toda a ROM", "Superior ao halter pelo estímulo consistente"],
    substituteIds: ["shoulder_elevacao_lateral"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "side_delt", "cable", "constant_tension"],
  },

  // ── TRÍCEPS ───────────────────────────────────────────────────

  {
    id: "triceps_testa_barra_w",
    name: "Tríceps Testa (Barra W/EZ)",
    nameEn: "EZ Bar Skull Crusher",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["barbell"],
    environment: ["full_gym", "basic_gym"],
    category: "isolation",
    difficulty: "intermediate",
    restrictions: ["elbow"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Cotovelos fixos apontando ao teto durante toda a ROM", "Barra desce até a testa — ROM completa", "Controle excêntrico de 3s (protocolo Alfredson)"],
    substituteIds: ["triceps_testa_halteres"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "triceps", "long_head"],
  },
  {
    id: "triceps_testa_halteres",
    name: "Tríceps Testa com Halteres",
    nameEn: "Dumbbell Skull Crushers",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["dumbbell", "bench"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Halteres paralelos — pegada neutra", "ROM completa — ao lado da cabeça", "Cotovelos fixos"],
    substituteIds: ["triceps_polia_corda"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "triceps", "home_friendly", "long_head"],
  },
  {
    id: "triceps_polia_corda",
    name: "Tríceps na Polia (Corda)",
    nameEn: "Tricep Rope Pushdown",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["cable"],
    environment: ["full_gym", "basic_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 12, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Abre a corda no final para contração máxima", "Cotovelos colados ao corpo", "ROM completa — braços totalmente estendidos"],
    substituteIds: ["triceps_frances"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "triceps", "lateral_head", "cable"],
  },
  {
    id: "triceps_frances",
    name: "Tríceps Francês (Haltere Overhead)",
    nameEn: "Overhead Tricep Extension",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: ["shoulder", "elbow"],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Cotovelos apontando ao teto — não abrir", "ROM completa — halter desce atrás da cabeça", "Máximo estiramento do longo do tríceps"],
    substituteIds: ["triceps_polia_corda"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "triceps", "long_head", "home_friendly", "overhead"],
  },
  {
    id: "triceps_mergulho_banco",
    name: "Mergulho no Banco (Tríceps)",
    nameEn: "Bench Dip",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    movementPattern: "push_vertical",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "compound",
    difficulty: "beginner",
    restrictions: ["shoulder"],
    repRangeMin: 10, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Desça até 90° de flexão no cotovelo — não mais profundo", "Pés próximos ao banco para menor carga", "ROM completa na subida — cotovelos estendidos"],
    substituteIds: ["triceps_polia_corda"],
    progressionIds: [],
    regressionIds: [],
    tags: ["bodyweight", "triceps", "home_friendly", "no_equipment"],
  },

  // ── BÍCEPS ────────────────────────────────────────────────────

  {
    id: "biceps_rosca_barra_w",
    name: "Rosca Direta (Barra W/EZ)",
    nameEn: "EZ Bar Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["barbell"],
    environment: ["full_gym", "basic_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — braços totalmente estendidos na descida", "Cotovelo vai levemente para trás no topo para contração máxima", "Pegada anatômica da EZ reduz tensão no punho"],
    substituteIds: ["biceps_rosca_haltere_alternada"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "biceps", "barbell"],
  },
  {
    id: "biceps_rosca_haltere_alternada",
    name: "Rosca Alternada com Halteres",
    nameEn: "Alternating Dumbbell Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Supine no topo — vire a palma para cima na subida", "ROM completa — braço totalmente estendido na descida", "Cotovelo levemente para trás no topo"],
    substituteIds: ["biceps_rosca_barra_w"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "biceps", "home_friendly", "unilateral"],
  },
  {
    id: "biceps_rosca_martelo",
    name: "Rosca Martelo",
    nameEn: "Hammer Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["brachialis"],
    movementPattern: "isolation",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Pegada neutra — polegar para cima durante todo o movimento", "ROM completa", "Desenvolve o braquial que empurra o bíceps para cima"],
    substituteIds: ["biceps_rosca_haltere_alternada"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "biceps", "brachialis", "home_friendly"],
  },

  // ── QUADRÍCEPS ────────────────────────────────────────────────

  {
    id: "quad_agachamento_barra",
    name: "Agachamento Livre com Barra",
    nameEn: "Barbell Back Squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core", "hamstrings"],
    movementPattern: "squat",
    equipment: ["barbell"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "advanced",
    restrictions: ["knee", "lower_back"],
    repRangeMin: 5, repRangeMax: 10,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — quebre a paralela (joelhos passam 90°) — Bloomquist 2013", "Calcanhares no chão — não eleve", "Joelhos sobre o dedo mindinho do pé", "Peito estufado, lombar neutra"],
    substituteIds: ["quad_leg_press", "quad_agachamento_goblet"],
    progressionIds: [],
    regressionIds: ["quad_agachamento_goblet"],
    tags: ["compound", "quads", "squat", "king_exercise", "pr_candidate"],
  },
  {
    id: "quad_agachamento_goblet",
    name: "Agachamento Goblet",
    nameEn: "Goblet Squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["core", "glutes"],
    movementPattern: "squat",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "beginner",
    restrictions: ["lower_back"],
    repRangeMin: 10, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Halter colado ao peito", "ROM completa — cotovelos entre os joelhos na descida", "Tronco ereto — não incline para frente"],
    substituteIds: ["quad_leg_press"],
    progressionIds: ["quad_agachamento_barra"],
    regressionIds: ["quad_agachamento_mini"],
    tags: ["compound", "quads", "squat", "beginner_friendly", "home_friendly"],
  },
  {
    id: "quad_leg_press",
    name: "Leg Press 45°",
    nameEn: "Leg Press",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "hamstrings"],
    movementPattern: "squat",
    equipment: ["machine"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "beginner",
    restrictions: ["lower_back"],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — joelhos até o peito", "Não estenda os joelhos totalmente", "Pés na largura do ombro no centro da plataforma", "Lombar colada ao banco"],
    substituteIds: ["quad_agachamento_goblet"],
    progressionIds: [],
    regressionIds: [],
    tags: ["compound", "quads", "machine", "knee_safe"],
  },
  {
    id: "quad_agachamento_bulgaro",
    name: "Agachamento Búlgaro",
    nameEn: "Bulgarian Split Squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "hamstrings"],
    movementPattern: "squat",
    equipment: ["dumbbell", "bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["knee"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Pé traseiro no banco a altura de joelho", "ROM completa — joelho traseiro quase toca o chão", "Tronco levemente inclinado para frente", "Joelho dianteiro alinhado sobre o pé"],
    substituteIds: ["quad_afundo_halteres"],
    progressionIds: ["quad_pistol_squat"],
    regressionIds: ["quad_afundo_halteres"],
    tags: ["compound", "quads", "unilateral", "glutes", "home_friendly"],
  },
  {
    id: "quad_afundo_halteres",
    name: "Avanço (Afundo) com Halteres",
    nameEn: "Dumbbell Lunge",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "hamstrings"],
    movementPattern: "squat",
    equipment: ["dumbbell", "bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["knee"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Passada larga", "Joelho traseiro quase toca o chão — ROM completa", "Tronco ereto"],
    substituteIds: ["quad_agachamento_bulgaro"],
    progressionIds: ["quad_agachamento_bulgaro"],
    regressionIds: [],
    tags: ["compound", "quads", "unilateral", "home_friendly"],
  },
  {
    id: "quad_cadeira_extensora",
    name: "Cadeira Extensora",
    nameEn: "Leg Extension",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["machine"],
    environment: ["full_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: ["knee"],
    repRangeMin: 12, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — extensão total", "Segure 1s no topo para contração máxima", "Ajuste o banco — parte de trás do joelho na borda"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "quads", "machine"],
  },

  // ── POSTERIORES / GLÚTEOS ─────────────────────────────────────

  {
    id: "ham_stiff_halteres",
    name: "Levantamento Romeno com Halteres (RDL)",
    nameEn: "Dumbbell Romanian Deadlift",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "lower_back"],
    movementPattern: "hinge",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "beginner",
    restrictions: ["lower_back"],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — tronco até a paralela ou abaixo se flexibilidade permitir", "Jogue o quadril para trás — não arredonde a lombar", "Halteres ao lado das coxas — não à frente"],
    substituteIds: ["ham_stiff_barra"],
    progressionIds: ["ham_stiff_barra"],
    regressionIds: [],
    tags: ["compound", "hamstrings", "hinge", "home_friendly"],
  },
  {
    id: "ham_stiff_barra",
    name: "Levantamento Romeno com Barra (RDL)",
    nameEn: "Barbell Romanian Deadlift",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "lower_back"],
    movementPattern: "hinge",
    equipment: ["barbell"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: ["lower_back"],
    repRangeMin: 6, repRangeMax: 10,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — barra desce pela perna até abaixo dos joelhos", "Barra rente ao corpo durante todo o movimento", "Joelhos levemente flexionados"],
    substituteIds: ["ham_stiff_halteres"],
    progressionIds: ["ham_levantamento_terra"],
    regressionIds: ["ham_stiff_halteres"],
    tags: ["compound", "hamstrings", "hinge", "glutes"],
  },
  {
    id: "ham_levantamento_terra",
    name: "Levantamento Terra Convencional",
    nameEn: "Conventional Deadlift",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "back", "quads", "core"],
    movementPattern: "hinge",
    equipment: ["barbell"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "advanced",
    restrictions: ["lower_back"],
    repRangeMin: 3, repRangeMax: 6,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Barra sobre o mediopé", "Barra rente ao corpo durante todo o movimento", "Empurre o chão — não puxe a barra", "Core braced — Valsalva controlada"],
    substituteIds: ["ham_stiff_barra"],
    progressionIds: [],
    regressionIds: ["ham_stiff_barra"],
    tags: ["compound", "hamstrings", "hinge", "full_body", "strength", "pr_candidate"],
  },
  {
    id: "ham_mesa_flexora",
    name: "Mesa Flexora",
    nameEn: "Lying Leg Curl",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["machine"],
    environment: ["full_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — calcanhar vai ao glúteo", "Pressione o quadril no banco", "Pause 1s no topo para contração máxima"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "hamstrings", "machine"],
  },
  {
    id: "glute_hip_thrust_barra",
    name: "Hip Thrust com Barra",
    nameEn: "Barbell Hip Thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "quads"],
    movementPattern: "hinge",
    equipment: ["barbell", "bench"],
    environment: ["full_gym"],
    category: "compound",
    difficulty: "intermediate",
    restrictions: [],
    repRangeMin: 8, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — quadril até a extensão máxima", "Esmague os glúteos no topo — pausa 1s", "Joelhos dobrados a 90° no topo", "Queixo no peito — não hiperestenda o pescoço"],
    substituteIds: ["glute_hip_thrust_haltere"],
    progressionIds: [],
    regressionIds: ["glute_hip_thrust_haltere"],
    tags: ["compound", "glutes", "hinge", "knee_safe", "pr_candidate"],
  },
  {
    id: "glute_hip_thrust_haltere",
    name: "Hip Thrust com Haltere",
    nameEn: "Dumbbell Hip Thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    movementPattern: "hinge",
    equipment: ["dumbbell", "bench"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Ombros apoiados no banco", "Halter no quadril — segure firme", "ROM completa — quadril totalmente estendido no topo"],
    substituteIds: ["glute_ponte_solo"],
    progressionIds: ["glute_hip_thrust_barra"],
    regressionIds: ["glute_ponte_solo"],
    tags: ["compound", "glutes", "home_friendly", "knee_safe"],
  },
  {
    id: "glute_ponte_solo",
    name: "Ponte de Glúteos no Solo",
    nameEn: "Glute Bridge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    movementPattern: "hinge",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 15, repRangeMax: 25,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Pés próximos ao glúteo — joelhos a 90°", "ROM completa — quadril totalmente estendido no topo", "Esmague os glúteos — pausa 2s no topo"],
    substituteIds: [],
    progressionIds: ["glute_hip_thrust_haltere"],
    regressionIds: [],
    tags: ["bodyweight", "glutes", "home_friendly", "no_equipment", "rehab_friendly"],
  },

  // ── PANTURRILHA ───────────────────────────────────────────────

  {
    id: "calf_em_pe_maquina",
    name: "Panturrilha em Pé (Máquina)",
    nameEn: "Standing Calf Raise",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["machine"],
    environment: ["full_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 12, repRangeMax: 20,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — calcanhar abaixo da plataforma na descida", "Pause 1s no topo em contração máxima", "Não use impulso — movimento controlado"],
    substituteIds: ["calf_bodyweight_degrau"],
    progressionIds: [],
    regressionIds: [],
    tags: ["isolation", "calves", "machine"],
  },
  {
    id: "calf_bodyweight_degrau",
    name: "Panturrilha no Degrau (Peso do Corpo)",
    nameEn: "Bodyweight Calf Raise",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 20, repRangeMax: 40,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — calcanhar abaixo do degrau na descida", "Pause no topo", "Progrida para unilateral quando ficar fácil"],
    substituteIds: [],
    progressionIds: ["calf_unilateral_lastro"],
    regressionIds: [],
    tags: ["bodyweight", "calves", "home_friendly", "no_equipment"],
  },
  {
    id: "calf_unilateral_lastro",
    name: "Panturrilha Unilateral com Lastro",
    nameEn: "Single Leg Weighted Calf Raise",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["dumbbell", "bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight"],
    category: "isolation",
    difficulty: "intermediate",
    restrictions: [],
    repRangeMin: 12, repRangeMax: 20,
    isUnilateral: true,
    gifUrl: null,
    cues: ["ROM completa — maior amplitude que bilateral", "Halter na mão do lado trabalhado", "Controle excêntrico lento"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: ["calf_bodyweight_degrau"],
    tags: ["calves", "unilateral", "home_friendly"],
  },

  // ── CORE / ABDÔMEN ────────────────────────────────────────────

  {
    id: "core_prancha",
    name: "Prancha Abdominal",
    nameEn: "Plank",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["core", "shoulders"],
    movementPattern: "isometric",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 20, repRangeMax: 60,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Corpo reto — não deixe o quadril cair", "Core ativado — respire com controle", "Progrida em tempo — 20s, 30s, 45s, 60s"],
    substituteIds: [],
    progressionIds: ["core_prancha_com_toque"],
    regressionIds: [],
    tags: ["core", "isometric", "home_friendly", "lower_back_safe", "no_equipment"],
  },
  {
    id: "core_elevacao_pernas_suspenso",
    name: "Elevação de Pernas (Suspenso na Barra)",
    nameEn: "Hanging Leg Raise",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["hip_flexors"],
    movementPattern: "isolation",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym"],
    category: "isolation",
    difficulty: "intermediate",
    restrictions: ["lower_back", "shoulder"],
    repRangeMin: 8, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["ROM completa — pernas até a paralela ou além", "Sem balanço", "Controle a descida em 2–3s"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: ["core_prancha"],
    tags: ["core", "abs", "bodyweight"],
  },

  // ── REABILITAÇÃO ──────────────────────────────────────────────

  {
    id: "rehab_manguito_rotador_externo",
    name: "Rotação Externa de Ombro (Cabo)",
    nameEn: "Cable External Rotation",
    primaryMuscles: ["rotator_cuff"],
    secondaryMuscles: [],
    movementPattern: "isolation",
    equipment: ["cable"],
    environment: ["full_gym", "basic_gym"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 15, repRangeMax: 20,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Cotovelo a 90° colado ao corpo", "ROM completa — rotação máxima", "Movimento lento e controlado — sem compensação"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["rehab", "shoulder", "rotator_cuff", "prevention"],
  },
  {
    id: "rehab_ombro_y_t_w",
    name: "Exercício Y-T-W (Haltere Leve)",
    nameEn: "YTW Raises",
    primaryMuscles: ["rear_delt"],
    secondaryMuscles: ["rotator_cuff", "back"],
    movementPattern: "isolation",
    equipment: ["dumbbell"],
    environment: ["full_gym", "basic_gym", "home_dumbbell"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 12, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Halteres muito leves (1–5 kg)", "Deite no banco inclinado para apoio", "Ative escápulas em cada posição"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["rehab", "shoulder", "scapular_stability", "prevention"],
  },
  {
    id: "rehab_joelho_step_up",
    name: "Step Up (Subida no Degrau)",
    nameEn: "Step Up",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    movementPattern: "squat",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "compound",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 12, repRangeMax: 15,
    isUnilateral: true,
    gifUrl: null,
    cues: ["Sobe com o calcanhar — não com os dedos", "ROM completa — extensão total do joelho no topo", "Controla a descida"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["rehab", "knee", "unilateral", "functional", "no_equipment"],
  },
  {
    id: "rehab_lombar_bird_dog",
    name: "Bird Dog (Cão-Pássaro)",
    nameEn: "Bird Dog",
    primaryMuscles: ["core"],
    secondaryMuscles: ["lower_back", "glutes"],
    movementPattern: "isometric",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 10, repRangeMax: 15,
    isUnilateral: false,
    gifUrl: null,
    cues: ["4 apoios no chão", "Estenda braço e perna opostos simultaneamente", "Coluna neutra durante todo o movimento", "Pause 2s na extensão"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["rehab", "lower_back", "core_stability", "prevention", "no_equipment"],
  },
  {
    id: "rehab_lombar_dead_bug",
    name: "Dead Bug (Inseto Morto)",
    nameEn: "Dead Bug",
    primaryMuscles: ["core"],
    secondaryMuscles: ["lower_back"],
    movementPattern: "isometric",
    equipment: ["bodyweight"],
    environment: ["full_gym", "basic_gym", "home_dumbbell", "home_bodyweight", "outdoor"],
    category: "isolation",
    difficulty: "beginner",
    restrictions: [],
    repRangeMin: 8, repRangeMax: 12,
    isUnilateral: false,
    gifUrl: null,
    cues: ["Lombar COLADA ao chão durante todo o movimento", "Braço e perna opostos", "Respiração controlada — expire na extensão"],
    substituteIds: [],
    progressionIds: [],
    regressionIds: [],
    tags: ["rehab", "lower_back", "core_stability", "prevention", "no_equipment"],
  },
];

async function seedExercises() {
  console.log(`Iniciando seed de ${exercises.length} exercícios...`);
  const batch = db.batch();
  let count = 0;

  for (const ex of exercises) {
    const { id, ...data } = ex;
    const ref = db.collection("exercises").doc(id);
    batch.set(ref, {
      ...data,
      updatedAt: admin.firestore.Timestamp.now(),
    });
    count++;
    // Firestore batch limit é 500 writes
    if (count % 400 === 0) {
      await batch.commit();
      console.log(`  Commit parcial: ${count} exercícios`);
    }
  }

  await batch.commit();
  console.log(`✅ Seed concluído: ${count} exercícios escritos na coleção 'exercises'.`);
}

seedExercises().catch((err) => {
  console.error("❌ Erro no seed:", err);
  process.exit(1);
});
